//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup:visible.
        /// </summary>
        internal static string AccountDialog {
            get {
                return ResourceManager.GetString("AccountDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #band-btn-cancel:visible.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #btn-change-password:visible.
        /// </summary>
        internal static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-company input:visible.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Company required&quot;):visible.
        /// </summary>
        internal static string ErrorCompanyRequired {
            get {
                return ResourceManager.GetString("ErrorCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;This does not match the expected pattern&quot;):visible.
        /// </summary>
        internal static string ErrorDoesNotMatchPattern {
            get {
                return ResourceManager.GetString("ErrorDoesNotMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Family name required&quot;):visible.
        /// </summary>
        internal static string ErrorFamilyNameRequired {
            get {
                return ResourceManager.GetString("ErrorFamilyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Given name required&quot;):visible.
        /// </summary>
        internal static string ErrorGivenNameRequired {
            get {
                return ResourceManager.GetString("ErrorGivenNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;This must have at least 3 characters&quot;):visible.
        /// </summary>
        internal static string ErrorMustHave3Chars {
            get {
                return ResourceManager.GetString("ErrorMustHave3Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;This must have at least 8 characters&quot;):visible.
        /// </summary>
        internal static string ErrorMustHave8Chars {
            get {
                return ResourceManager.GetString("ErrorMustHave8Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;This must have at least 9 characters&quot;):visible.
        /// </summary>
        internal static string ErrorMustHave9Chars {
            get {
                return ResourceManager.GetString("ErrorMustHave9Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;New password required&quot;):visible.
        /// </summary>
        internal static string ErrorNewPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Not more than 20 characters are allowed&quot;):visible.
        /// </summary>
        internal static string ErrorNotMore20Chars {
            get {
                return ResourceManager.GetString("ErrorNotMore20Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Old password required&quot;):visible.
        /// </summary>
        internal static string ErrorOldPasswordRequired {
            get {
                return ResourceManager.GetString("ErrorOldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Password repeat required&quot;):visible.
        /// </summary>
        internal static string ErrorPasswordRepeatRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordRepeatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Passwords do not match&quot;):visible.
        /// </summary>
        internal static string ErrorPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Phone required&quot;):visible.
        /// </summary>
        internal static string ErrorPhoneRequired {
            get {
                return ResourceManager.GetString("ErrorPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-family-name input:visible.
        /// </summary>
        internal static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-given-name input:visible.
        /// </summary>
        internal static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-new-password input:visible.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal #Ok:visible.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-ok.
        /// </summary>
        internal static string OkButton2 {
            get {
                return ResourceManager.GetString("OkButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-old-password input:visible.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.vb-modal-content:contains(&quot;The old password you&quot;):visible.
        /// </summary>
        internal static string OldPasswordIncorrectDialog {
            get {
                return ResourceManager.GetString("OldPasswordIncorrectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.vb-modal-content:contains(&quot;Entered password is blacklisted&quot;):visible.
        /// </summary>
        internal static string PasswordBlacklistedDialog {
            get {
                return ResourceManager.GetString("PasswordBlacklistedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-password-repeat input:visible.
        /// </summary>
        internal static string PasswordRepeat {
            get {
                return ResourceManager.GetString("PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #inp-phone input:visible.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-account-popup #band-btn-submit:visible.
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
    }
}
