//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdvancedFilter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdvancedFilter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.AdvancedFilter", typeof(AdvancedFilter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-apply:visible.
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-close:visible.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-date-picker.created-from input#input.
        /// </summary>
        internal static string Created1 {
            get {
                return ResourceManager.GetString("Created1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-date-picker.created-to input#input.
        /// </summary>
        internal static string Created2 {
            get {
                return ResourceManager.GetString("Created2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-created span.selection:visible.
        /// </summary>
        internal static string CreatedDropDown {
            get {
                return ResourceManager.GetString("CreatedDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vaadin-date-picker-overlay:visible.
        /// </summary>
        internal static string DatePicker {
            get {
                return ResourceManager.GetString("DatePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vaadin-date-picker-overlay div.vaadin-month-calendar[aria-label^=&quot;{0}&quot;]:visible.
        /// </summary>
        internal static string DatePickerDateByText {
            get {
                return ResourceManager.GetString("DatePickerDateByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vaadin-date-picker-overlay div.vaadin-month-calendar[aria-label^=&quot;{0}&quot;][focused]:visible.
        /// </summary>
        internal static string DatePickerDateSelectedByText {
            get {
                return ResourceManager.GetString("DatePickerDateSelectedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-date-picker.modified-from input#input.
        /// </summary>
        internal static string Modified1 {
            get {
                return ResourceManager.GetString("Modified1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-date-picker.modified-to input#input.
        /// </summary>
        internal static string Modified2 {
            get {
                return ResourceManager.GetString("Modified2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-modified span.selection:visible.
        /// </summary>
        internal static string ModifiedDropDown {
            get {
                return ResourceManager.GetString("ModifiedDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-reset:visible.
        /// </summary>
        internal static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.group__status span.selection:visible.
        /// </summary>
        internal static string StatusDropDown {
            get {
                return ResourceManager.GetString("StatusDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.group__status span.selection li:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string StatusDropDownSelectionByText {
            get {
                return ResourceManager.GetString("StatusDropDownSelectionByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.group__status span.selection li:contains(&quot;{0}&quot;) span.select2-selection__choice__remove:visible.
        /// </summary>
        internal static string StatusDropDownSelectionByTextDeleteButton {
            get {
                return ResourceManager.GetString("StatusDropDownSelectionByTextDeleteButton", resourceCulture);
            }
        }
    }
}
