//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.AppsPage", typeof(AppsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-accuracy input:visible.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-accuracy div[title].
        /// </summary>
        internal static string AccuracyReadOnly {
            get {
                return ResourceManager.GetString("AccuracyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar .active.
        /// </summary>
        internal static string ActiveLanguageTab {
            get {
                return ResourceManager.GetString("ActiveLanguageTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-add[ng-reflect-disabled!=&quot;true&quot;].
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-add[ng-reflect-disabled=&quot;true&quot;].
        /// </summary>
        internal static string AddButtonDisabled {
            get {
                return ResourceManager.GetString("AddButtonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-address1 textarea.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-addresses vb-button#btn-add span.vb-icon:visible.
        /// </summary>
        internal static string AddressAddButton {
            get {
                return ResourceManager.GetString("AddressAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #arr-row-addresses-1.
        /// </summary>
        internal static string AddressLine1 {
            get {
                return ResourceManager.GetString("AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #arr-row-addresses-2.
        /// </summary>
        internal static string AddressLine2 {
            get {
                return ResourceManager.GetString("AddressLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #arr-row-addresses-3.
        /// </summary>
        internal static string AddressLine3 {
            get {
                return ResourceManager.GetString("AddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button.vb-btn-del-row.vb-button:visible.
        /// </summary>
        internal static string AddressLineDeleteButtonsVisible {
            get {
                return ResourceManager.GetString("AddressLineDeleteButtonsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-address1 div.vb-form-input.
        /// </summary>
        internal static string AddressReadOnly {
            get {
                return ResourceManager.GetString("AddressReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount First.
        /// </summary>
        internal static string AmountFirstItem {
            get {
                return ResourceManager.GetString("AmountFirstItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-app-title input.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-app-title .vb-control-label.
        /// </summary>
        internal static string AppTitleLabel {
            get {
                return ResourceManager.GetString("AppTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-notification-area span:contains(&quot;Speaking name of the app&quot;).
        /// </summary>
        internal static string AppTitleNotification {
            get {
                return ResourceManager.GetString("AppTitleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-app-title div[title].
        /// </summary>
        internal static string AppTitleReadOnly {
            get {
                return ResourceManager.GetString("AppTitleReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-area input:visible.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-beacon:has(img[src*=&quot;arrow&quot;]):visible.
        /// </summary>
        internal static string BeaconButton {
            get {
                return ResourceManager.GetString("BeaconButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-car-details:visible.
        /// </summary>
        internal static string CarDetailsButton {
            get {
                return ResourceManager.GetString("CarDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;your changes will be discarded&quot;).
        /// </summary>
        internal static string ChangesWillBeDiscardedDialog {
            get {
                return ResourceManager.GetString("ChangesWillBeDiscardedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-clear-selection.
        /// </summary>
        internal static string ClearSelectionButton {
            get {
                return ResourceManager.GetString("ClearSelectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #txt-created div:not([class]).
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th:contains(&quot;Created by&quot;).
        /// </summary>
        internal static string CreatedByColumn {
            get {
                return ResourceManager.GetString("CreatedByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;cross-language master data values to be overwritten&quot;):visible.
        /// </summary>
        internal static string CrossLanguageMdValuesOverwrittenDialog {
            get {
                return ResourceManager.GetString("CrossLanguageMdValuesOverwrittenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency First.
        /// </summary>
        internal static string CurrencyFirstItem {
            get {
                return ResourceManager.GetString("CurrencyFirstItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-currency-formatting span.selection:visible.
        /// </summary>
        internal static string CurrencyFormattingDropDown {
            get {
                return ResourceManager.GetString("CurrencyFormattingDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-currency-formatting div[title].
        /// </summary>
        internal static string CurrencyFormattingReadOnly {
            get {
                return ResourceManager.GetString("CurrencyFormattingReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-default-currency input.
        /// </summary>
        internal static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-default-currency div[title].
        /// </summary>
        internal static string DefaultCurrencyReadOnly {
            get {
                return ResourceManager.GetString("DefaultCurrencyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-delete.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;want to delete&quot;).
        /// </summary>
        internal static string DeleteConfirmationDialog {
            get {
                return ResourceManager.GetString("DeleteConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-description textarea.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-description div[title].
        /// </summary>
        internal static string DescriptionReadOnly {
            get {
                return ResourceManager.GetString("DescriptionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-deselect-all:visible.
        /// </summary>
        internal static string DeselectAllButton {
            get {
                return ResourceManager.GetString("DeselectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #txt-device-type div:not([class]).
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th:contains(&quot;Device Type&quot;).
        /// </summary>
        internal static string DeviceTypeColumn {
            get {
                return ResourceManager.GetString("DeviceTypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #sl-display-brightness input.
        /// </summary>
        internal static string DisplayBrightness {
            get {
                return ResourceManager.GetString("DisplayBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #sl-display-brightness .vb-units span.transparent.
        /// </summary>
        internal static string DisplayBrightnessVal {
            get {
                return ResourceManager.GetString("DisplayBrightnessVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.title:contains(&quot;Master Data&quot;).
        /// </summary>
        internal static string DistributeMdDialog {
            get {
                return ResourceManager.GetString("DistributeMdDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-arr-row[data-lev*=&quot;{0}&quot;]:contains(&quot;{1}&quot;).
        /// </summary>
        internal static string DistributeMdRowByParentText {
            get {
                return ResourceManager.GetString("DistributeMdRowByParentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-arr-row:contains(&quot;{0}&quot;).
        /// </summary>
        internal static string DistributeMdRowByText {
            get {
                return ResourceManager.GetString("DistributeMdRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-selected-partial:contains(&quot;{0}&quot;).
        /// </summary>
        internal static string DistributeMdSelectedPartialRowByText {
            get {
                return ResourceManager.GetString("DistributeMdSelectedPartialRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-selected-partial.
        /// </summary>
        internal static string DistributeMdSelectedPartialRows {
            get {
                return ResourceManager.GetString("DistributeMdSelectedPartialRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-selected:contains(&quot;{0}&quot;).
        /// </summary>
        internal static string DistributeMdSelectedRowByText {
            get {
                return ResourceManager.GetString("DistributeMdSelectedRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-selected.
        /// </summary>
        internal static string DistributeMdSelectedRows {
            get {
                return ResourceManager.GetString("DistributeMdSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-arr-row:not(.vb-selected):not(.vb-selected-partial):contains(&quot;{0}&quot;).
        /// </summary>
        internal static string DistributeMdUnselectedRowByText {
            get {
                return ResourceManager.GetString("DistributeMdUnselectedRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-prop-list div.vb-arr-row:not(.vb-selected):not(.vb-selected-partial).
        /// </summary>
        internal static string DistributeMdUnselectedRows {
            get {
                return ResourceManager.GetString("DistributeMdUnselectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;distribute/overwrite the following items&quot;):visible.
        /// </summary>
        internal static string DistributeOverwriteFollowingItemsDialog {
            get {
                return ResourceManager.GetString("DistributeOverwriteFollowingItemsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-email-body textarea.
        /// </summary>
        internal static string EmailBodyInNewCars {
            get {
                return ResourceManager.GetString("EmailBodyInNewCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-email-body textarea.
        /// </summary>
        internal static string EmailBodyInUsedCars {
            get {
                return ResourceManager.GetString("EmailBodyInUsedCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-emails:visible.
        /// </summary>
        internal static string EmailsButton {
            get {
                return ResourceManager.GetString("EmailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-email-subject input.
        /// </summary>
        internal static string EmailSubjectInNewCars {
            get {
                return ResourceManager.GetString("EmailSubjectInNewCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-email-subject input.
        /// </summary>
        internal static string EmailSubjectInUsedCars {
            get {
                return ResourceManager.GetString("EmailSubjectInUsedCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-goodbye-message #ch-box-enable div.vb-checkbox-btn.
        /// </summary>
        internal static string EnableInGoodByeMessageCheckBox {
            get {
                return ResourceManager.GetString("EnableInGoodByeMessageCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-address1 div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorAddressTooShort {
            get {
                return ResourceManager.GetString("ErrorAddressTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class~=&quot;vb-modal-content&quot;]:contains(&quot;title is used by another app&quot;).
        /// </summary>
        internal static string ErrorAppTitleIsUsedDialog {
            get {
                return ResourceManager.GetString("ErrorAppTitleIsUsedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-area div.vb-validation-msg:visible.
        /// </summary>
        internal static string ErrorArea {
            get {
                return ResourceManager.GetString("ErrorArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;can not be deleted&quot;).
        /// </summary>
        internal static string ErrorCantBeDeletedDialog {
            get {
                return ResourceManager.GetString("ErrorCantBeDeletedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-default-currency div.vb-validation-msg:visible.
        /// </summary>
        internal static string ErrorDefaultCurrencyPlaceholderForErrorMsg {
            get {
                return ResourceManager.GetString("ErrorDefaultCurrencyPlaceholderForErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Default currency required&quot;):visible.
        /// </summary>
        internal static string ErrorDefaultCurrencyRequired {
            get {
                return ResourceManager.GetString("ErrorDefaultCurrencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Not more than 3 characters are allowed&quot;):visible.
        /// </summary>
        internal static string ErrorDefaultCurrencyTooLong {
            get {
                return ResourceManager.GetString("ErrorDefaultCurrencyTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb-validation-msg:contains(&quot;This must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorDefaultCurrencyTooShort {
            get {
                return ResourceManager.GetString("ErrorDefaultCurrencyTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;does not match the expected pattern&quot;):visible.
        /// </summary>
        internal static string ErrorDoesNotMatchPattern {
            get {
                return ResourceManager.GetString("ErrorDoesNotMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-email-body div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorEmailBodyInNewCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorEmailBodyInNewCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-email-body div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorEmailBodyInUsedCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorEmailBodyInUsedCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-email-subject div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorEmailSubjectInNewCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorEmailSubjectInNewCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-email-subject div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorEmailSubjectInUsedCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorEmailSubjectInUsedCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #btn-goodbye-message div.vb-validation-msg:contains(&quot;Configuration is not valid&quot;):visible.
        /// </summary>
        internal static string ErrorGoodByeMessageButtonConfigurationIsNotValid {
            get {
                return ResourceManager.GetString("ErrorGoodByeMessageButtonConfigurationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.vb-modal-content:contains(&quot;lost internet connection&quot;):visible.
        /// </summary>
        internal static string ErrorInternetConnectionLostDialog {
            get {
                return ResourceManager.GetString("ErrorInternetConnectionLostDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class~=&quot;vb-modal-content&quot;]:contains(&quot;is not a version of&quot;).
        /// </summary>
        internal static string ErrorIsNotAVersionDialog {
            get {
                return ResourceManager.GetString("ErrorIsNotAVersionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-market div.vb-validation-msg:visible.
        /// </summary>
        internal static string ErrorMarket {
            get {
                return ResourceManager.GetString("ErrorMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-market-code div.vb-validation-msg:visible.
        /// </summary>
        internal static string ErrorMarketCodePlaceholderForErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMarketCodePlaceholderForErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Market code required&quot;):visible.
        /// </summary>
        internal static string ErrorMarketCodeRequired {
            get {
                return ResourceManager.GetString("ErrorMarketCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;Not more than 5 characters are allowed&quot;):visible.
        /// </summary>
        internal static string ErrorMarketCodeTooLong {
            get {
                return ResourceManager.GetString("ErrorMarketCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:contains(&quot;This must have at least 2 characters&quot;):visible.
        /// </summary>
        internal static string ErrorMarketCodeTooShort {
            get {
                return ResourceManager.GetString("ErrorMarketCodeTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-messenger div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorMessengertInNewCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorMessengertInNewCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-messenger div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorMessengertInUsedCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorMessengertInUsedCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div[class~=&quot;vb-modal-content&quot;]:contains(&quot;Exception during package importing&quot;):visible.
        /// </summary>
        internal static string ErrorPackageImportingWindow {
            get {
                return ResourceManager.GetString("ErrorPackageImportingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-region div.vb-validation-msg:visible.
        /// </summary>
        internal static string ErrorRegion {
            get {
                return ResourceManager.GetString("ErrorRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-salutation-no-profile .vb-validation-msg:contains(&quot;more than 50 characters&quot;):visible.
        /// </summary>
        internal static string ErrorSalutationNoProfileTooLong {
            get {
                return ResourceManager.GetString("ErrorSalutationNoProfileTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #btn-sharing-templates-for-new-cars div.vb-validation-msg:contains(&quot;Configuration is not valid&quot;):visible.
        /// </summary>
        internal static string ErrorSharingTemplatesForNewCarsButtonConfigurationIsNotValid {
            get {
                return ResourceManager.GetString("ErrorSharingTemplatesForNewCarsButtonConfigurationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #btn-sharing-templates-for-used-cars div.vb-validation-msg:contains(&quot;Configuration is not valid&quot;):visible.
        /// </summary>
        internal static string ErrorSharingTemplatesForUsedCarsButtonConfigurationIsNotValid {
            get {
                return ResourceManager.GetString("ErrorSharingTemplatesForUsedCarsButtonConfigurationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-showing-delay div.vb-validation-msg:contains(&quot;Showing delay required&quot;):visible.
        /// </summary>
        internal static string ErrorShowingDelayRequired {
            get {
                return ResourceManager.GetString("ErrorShowingDelayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-goodbye-message #inp-text div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorTextInGoodByeMessageTooShort {
            get {
                return ResourceManager.GetString("ErrorTextInGoodByeMessageTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #btn-texts div.vb-validation-msg:contains(&quot;Configuration is not valid&quot;):visible.
        /// </summary>
        internal static string ErrorTextsButtonConfigurationIsNotValid {
            get {
                return ResourceManager.GetString("ErrorTextsButtonConfigurationIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;no items&quot;).
        /// </summary>
        internal static string ErrorTheAreNoItemsDialog {
            get {
                return ResourceManager.GetString("ErrorTheAreNoItemsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-title div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorTitleTooShort {
            get {
                return ResourceManager.GetString("ErrorTitleTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-twitter div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorTwitterInNewCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorTwitterInNewCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-twitter div.vb-validation-msg:contains(&quot;must have at least one character&quot;):visible.
        /// </summary>
        internal static string ErrorTwitterInUsedCarsTooShort {
            get {
                return ResourceManager.GetString("ErrorTwitterInUsedCarsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class~=&quot;vb-modal-content&quot;]:contains(&quot;already exists for&quot;):visible.
        /// </summary>
        internal static string ErrorVersionAlreadyExistsDialog {
            get {
                return ResourceManager.GetString("ErrorVersionAlreadyExistsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-feature-accessibility:visible.
        /// </summary>
        internal static string FeatureAccessibilityButton {
            get {
                return ResourceManager.GetString("FeatureAccessibilityButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-goodbye-message:visible.
        /// </summary>
        internal static string GoodByeMessageButton {
            get {
                return ResourceManager.GetString("GoodByeMessageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-hiding-delay .vb-control-label.
        /// </summary>
        internal static string HidingDelayLabel {
            get {
                return ResourceManager.GetString("HidingDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-img-preview a img:not([src*=&quot;placeholder&quot;]).
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-img-tools #band-btn-remove:visible.
        /// </summary>
        internal static string ImageRemoveButton {
            get {
                return ResourceManager.GetString("ImageRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-img-tools #band-btn-replace:visible.
        /// </summary>
        internal static string ImageReplaceButton {
            get {
                return ResourceManager.GetString("ImageReplaceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-img-tools #band-btn-upload:visible.
        /// </summary>
        internal static string ImageUploadButton {
            get {
                return ResourceManager.GetString("ImageUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-imprint:visible.
        /// </summary>
        internal static string ImprintButton {
            get {
                return ResourceManager.GetString("ImprintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-imprint-url input.
        /// </summary>
        internal static string ImprintUrl {
            get {
                return ResourceManager.GetString("ImprintUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-imprint-url .vb-form-input span.
        /// </summary>
        internal static string ImprintUrlVal {
            get {
                return ResourceManager.GetString("ImprintUrlVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-information:visible.
        /// </summary>
        internal static string InformationButton {
            get {
                return ResourceManager.GetString("InformationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #s-prop-picture div.img-holder img:visible.
        /// </summary>
        internal static string InformationPicture {
            get {
                return ResourceManager.GetString("InformationPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #s-prop-picture div.img-holder:has(img[hidden]).
        /// </summary>
        internal static string InformationPictureEmpty {
            get {
                return ResourceManager.GetString("InformationPictureEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #s-prop-picture vb-button.vb-upload-btn:visible.
        /// </summary>
        internal static string InformationPictureUploadButton {
            get {
                return ResourceManager.GetString("InformationPictureUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-container-addresses #btn-add:visible.
        /// </summary>
        internal static string InformationSectionAddressesAddButton {
            get {
                return ResourceManager.GetString("InformationSectionAddressesAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-container-addresses #btn-cancel:visible.
        /// </summary>
        internal static string InformationSectionAddressesCancelButton {
            get {
                return ResourceManager.GetString("InformationSectionAddressesCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-container-addresses #btn-change-order:visible.
        /// </summary>
        internal static string InformationSectionAddressesChangeOrderButton {
            get {
                return ResourceManager.GetString("InformationSectionAddressesChangeOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-container-addresses #btn-done:visible.
        /// </summary>
        internal static string InformationSectionAddressesDoneButton {
            get {
                return ResourceManager.GetString("InformationSectionAddressesDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-row-addresses-1.
        /// </summary>
        internal static string InformationSectionAddressesRow1 {
            get {
                return ResourceManager.GetString("InformationSectionAddressesRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-row-addresses-2.
        /// </summary>
        internal static string InformationSectionAddressesRow2 {
            get {
                return ResourceManager.GetString("InformationSectionAddressesRow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-details-addresses-2 #inp-address textarea:visible.
        /// </summary>
        internal static string InformationSectionAddressesRow2Address {
            get {
                return ResourceManager.GetString("InformationSectionAddressesRow2Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-information #arr-details-addresses-2 #inp-title input:visible.
        /// </summary>
        internal static string InformationSectionAddressesRow2Title {
            get {
                return ResourceManager.GetString("InformationSectionAddressesRow2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-interior-color-disclaimer textarea.
        /// </summary>
        internal static string InteriorColorDisclaimer {
            get {
                return ResourceManager.GetString("InteriorColorDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-modal-content:contains(&quot;item is referenced&quot;).
        /// </summary>
        internal static string ItemIsReferencedDialog {
            get {
                return ResourceManager.GetString("ItemIsReferencedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span[class~=&quot;vb-band-label&quot;] span.vb-lang-btn-add:visible.
        /// </summary>
        internal static string LanguageAddButton {
            get {
                return ResourceManager.GetString("LanguageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span[class~=&quot;vb-band-label&quot;] span:contains(&quot;ar&quot;):visible.
        /// </summary>
        internal static string LanguageArButton {
            get {
                return ResourceManager.GetString("LanguageArButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-band-label.active:contains(&quot;ar&quot;).
        /// </summary>
        internal static string LanguageArButtonActive {
            get {
                return ResourceManager.GetString("LanguageArButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-band-label.menu-active span:contains(&quot;ar&quot;).
        /// </summary>
        internal static string LanguageArButtonActiveInMenu {
            get {
                return ResourceManager.GetString("LanguageArButtonActiveInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar vb-band-label:visible.
        /// </summary>
        internal static string LanguageBar {
            get {
                return ResourceManager.GetString("LanguageBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span[class~=&quot;vb-band-label&quot;] span:contains(&quot;de&quot;):visible.
        /// </summary>
        internal static string LanguageDeButton {
            get {
                return ResourceManager.GetString("LanguageDeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-band-label.active span:contains(&quot;de&quot;).
        /// </summary>
        internal static string LanguageDeButtonActive {
            get {
                return ResourceManager.GetString("LanguageDeButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-band-label.menu-active span:contains(&quot;de&quot;).
        /// </summary>
        internal static string LanguageDeButtonActiveInMenu {
            get {
                return ResourceManager.GetString("LanguageDeButtonActiveInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-band-label.invalid:contains(&quot;de&quot;).
        /// </summary>
        internal static string LanguageDeButtonInvalid {
            get {
                return ResourceManager.GetString("LanguageDeButtonInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-lang-btn-del:visible span:visible.
        /// </summary>
        internal static string LanguageDeleteButton {
            get {
                return ResourceManager.GetString("LanguageDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class~=&quot;vb-modal-content&quot;]:contains(&quot;delete this language&quot;).
        /// </summary>
        internal static string LanguageDeleteConfirmationDialog {
            get {
                return ResourceManager.GetString("LanguageDeleteConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span[class~=&quot;vb-band-label&quot;]:contains(&quot;en&quot;).
        /// </summary>
        internal static string LanguageEnButton {
            get {
                return ResourceManager.GetString("LanguageEnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-lang-bar span.vb-band-label.active:contains(&quot;en&quot;).
        /// </summary>
        internal static string LanguageEnButtonActive {
            get {
                return ResourceManager.GetString("LanguageEnButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-band-button#band-btn-mark-as-deleted.
        /// </summary>
        internal static string MarkAsDeletedButton {
            get {
                return ResourceManager.GetString("MarkAsDeletedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-market input.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-market:visible.
        /// </summary>
        internal static string MarketButton {
            get {
                return ResourceManager.GetString("MarketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-market-code input.
        /// </summary>
        internal static string MarketCode {
            get {
                return ResourceManager.GetString("MarketCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-market-code div[title].
        /// </summary>
        internal static string MarketCodeReadOnly {
            get {
                return ResourceManager.GetString("MarketCodeReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-market div[title].
        /// </summary>
        internal static string MarketReadOnly {
            get {
                return ResourceManager.GetString("MarketReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-messenger textarea.
        /// </summary>
        internal static string MessengerInNewCars {
            get {
                return ResourceManager.GetString("MessengerInNewCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-messenger div[title].
        /// </summary>
        internal static string MessengerInNewCarsReadOnly {
            get {
                return ResourceManager.GetString("MessengerInNewCarsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-messenger textarea.
        /// </summary>
        internal static string MessengerInUsedCars {
            get {
                return ResourceManager.GetString("MessengerInUsedCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-modal vb-band-button.default:visible.
        /// </summary>
        internal static string ModalDialogDefaultButton {
            get {
                return ResourceManager.GetString("ModalDialogDefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #txt-modified div:not([class]).
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th:contains(&quot;Modified&quot;).
        /// </summary>
        internal static string ModifiedColumn {
            get {
                return ResourceManager.GetString("ModifiedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) th:contains(&quot;Modified&quot;).
        /// </summary>
        internal static string ModifiedColumnModal {
            get {
                return ResourceManager.GetString("ModifiedColumnModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-next:visible.
        /// </summary>
        internal static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-next.vb-disabled:visible.
        /// </summary>
        internal static string NextDisabledButton {
            get {
                return ResourceManager.GetString("NextDisabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;no appropriate tenant to distribute&quot;).
        /// </summary>
        internal static string NoAppropriateTenantToDistributeDialog {
            get {
                return ResourceManager.GetString("NoAppropriateTenantToDistributeDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-no.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;no distributable properties&quot;).
        /// </summary>
        internal static string NoDistributablePropertiesDialog {
            get {
                return ResourceManager.GetString("NoDistributablePropertiesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-pin input:visible.
        /// </summary>
        internal static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-pin div[title].
        /// </summary>
        internal static string PinReadOnly {
            get {
                return ResourceManager.GetString("PinReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-sta li:visible.
        /// </summary>
        internal static string PlacesSection {
            get {
                return ResourceManager.GetString("PlacesSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-sta li:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string PlacesSectionPlaceByTitle {
            get {
                return ResourceManager.GetString("PlacesSectionPlaceByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-sta li:contains(&quot;{0}&quot;):visible img[src^=&quot;http&quot;].
        /// </summary>
        internal static string PlacesSectionPlaceByTitleAndPicture {
            get {
                return ResourceManager.GetString("PlacesSectionPlaceByTitleAndPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-profile-report-template span.selection:visible.
        /// </summary>
        internal static string ProfileReportTemplateDropDown {
            get {
                return ResourceManager.GetString("ProfileReportTemplateDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-profile-report-template span.vb-icon:visible.
        /// </summary>
        internal static string ProfileReportTemplateDropDownDetailsButton {
            get {
                return ResourceManager.GetString("ProfileReportTemplateDropDownDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-item-refs div.vb-app-list-ver span.vb-app-ver:contains(&quot;{0}&quot;).
        /// </summary>
        internal static string ReferencesSectionAppByTitle {
            get {
                return ResourceManager.GetString("ReferencesSectionAppByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-item-refs div.vb-app-list-ver.
        /// </summary>
        internal static string ReferencesSectionApps {
            get {
                return ResourceManager.GetString("ReferencesSectionApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-region input:visible.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-salutation-no-profile input.
        /// </summary>
        internal static string SalutationNoProfile {
            get {
                return ResourceManager.GetString("SalutationNoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-salutationwithoutprofile .vb-control-label.
        /// </summary>
        internal static string SalutationNoProfileLabel {
            get {
                return ResourceManager.GetString("SalutationNoProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-notification-area span:contains(&quot;Salutation no profile:&quot;).
        /// </summary>
        internal static string SalutationNoProfileNotification {
            get {
                return ResourceManager.GetString("SalutationNoProfileNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-salutation-no-profile div[title].
        /// </summary>
        internal static string SalutationNoProfileReadOnly {
            get {
                return ResourceManager.GetString("SalutationNoProfileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-salutationwithprofile textarea.
        /// </summary>
        internal static string SalutationProfile {
            get {
                return ResourceManager.GetString("SalutationProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-salutation-profile div[title].
        /// </summary>
        internal static string SalutationProfileReadOnly {
            get {
                return ResourceManager.GetString("SalutationProfileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-notification-content:contains(&quot;Save operation&quot;).
        /// </summary>
        internal static string SaveNotification {
            get {
                return ResourceManager.GetString("SaveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th:contains(&quot;Screenshot&quot;).
        /// </summary>
        internal static string ScreenshotColumn {
            get {
                return ResourceManager.GetString("ScreenshotColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-select-all:visible.
        /// </summary>
        internal static string SelectAllButton {
            get {
                return ResourceManager.GetString("SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.component-caption:contains(&quot;Items&quot;).
        /// </summary>
        internal static string SelectItemDialog {
            get {
                return ResourceManager.GetString("SelectItemDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal h1:contains(&quot;Items&quot;).
        /// </summary>
        internal static string SelectItemNewDialog {
            get {
                return ResourceManager.GetString("SelectItemNewDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients #btn-add.
        /// </summary>
        internal static string ServiceBookingRecipientAddButton {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients #btn-cancel:visible.
        /// </summary>
        internal static string ServiceBookingRecipientCancelButton {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients #btn-change-order:visible.
        /// </summary>
        internal static string ServiceBookingRecipientChangeOrderButton {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientChangeOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients vb-button.vb-arr-simple-btn-del.
        /// </summary>
        internal static string ServiceBookingRecipientDeleteButton {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients #btn-done:visible.
        /// </summary>
        internal static string ServiceBookingRecipientDoneButton {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientDoneButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients input:visible.
        /// </summary>
        internal static string ServiceBookingRecipientEmail {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients input:visible:last.
        /// </summary>
        internal static string ServiceBookingRecipientEmailLast {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientEmailLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients div[title].
        /// </summary>
        internal static string ServiceBookingRecipientEmailReadOnly {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientEmailReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-servicebookingrecipients div[title]:last.
        /// </summary>
        internal static string ServiceBookingRecipientEmailReadOnlyLast {
            get {
                return ResourceManager.GetString("ServiceBookingRecipientEmailReadOnlyLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-service-booking-template span.vb-icon.
        /// </summary>
        internal static string ServiceBookingTemplateDetailsButton {
            get {
                return ResourceManager.GetString("ServiceBookingTemplateDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ch-box-share-with-friends div.vb-checkbox-btn.
        /// </summary>
        internal static string ShareWithFriendsCheckBox {
            get {
                return ResourceManager.GetString("ShareWithFriendsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-sharing-templates-for-new-cars.
        /// </summary>
        internal static string SharingTemplatesForNewCarsButton {
            get {
                return ResourceManager.GetString("SharingTemplatesForNewCarsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-sharing-templates-for-used-cars.
        /// </summary>
        internal static string SharingTemplatesForUsedCarsButton {
            get {
                return ResourceManager.GetString("SharingTemplatesForUsedCarsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-showing-delay input.
        /// </summary>
        internal static string ShowingDelay {
            get {
                return ResourceManager.GetString("ShowingDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-showing-delay span:contains(&quot;-&quot;).
        /// </summary>
        internal static string ShowingDelayDecreaseButton {
            get {
                return ResourceManager.GetString("ShowingDelayDecreaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-showing-delay span:contains(&quot;+&quot;).
        /// </summary>
        internal static string ShowingDelayIncreaseButton {
            get {
                return ResourceManager.GetString("ShowingDelayIncreaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-showing-delay div[title].
        /// </summary>
        internal static string ShowingDelayReadOnly {
            get {
                return ResourceManager.GetString("ShowingDelayReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #txt-since div:not([class]).
        /// </summary>
        internal static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-state-reset-timer input:visible.
        /// </summary>
        internal static string StateResetTimer {
            get {
                return ResourceManager.GetString("StateResetTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-state-reset-timer div[title].
        /// </summary>
        internal static string StateResetTimerReadOnly {
            get {
                return ResourceManager.GetString("StateResetTimerReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-text#txt-status div:not([class]) span:visible.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th:contains(&quot;Status&quot;).
        /// </summary>
        internal static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) th:contains(&quot;Status&quot;).
        /// </summary>
        internal static string StatusColumnModal {
            get {
                return ResourceManager.GetString("StatusColumnModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td:contains(&quot;dpt&quot;).
        /// </summary>
        internal static string TableCellDptApp {
            get {
                return ResourceManager.GetString("TableCellDptApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td:contains(&quot;Beacon&quot;).
        /// </summary>
        internal static string TableCellIbeaconApp {
            get {
                return ResourceManager.GetString("TableCellIbeaconApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td[class~=&quot;vb-cell-status&quot;]:contains(&quot;{0}&quot;).
        /// </summary>
        internal static string TableCellStatus {
            get {
                return ResourceManager.GetString("TableCellStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td.dataTables_empty).
        /// </summary>
        internal static string TableEmpty {
            get {
                return ResourceManager.GetString("TableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbody tr:visible.
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;{0}&quot;)):visible.
        /// </summary>
        internal static string TableRowByText {
            get {
                return ResourceManager.GetString("TableRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;{0}&quot;)):has(td:contains(&quot;{1}&quot;)):has(td:contains(&quot;{2}&quot;)).
        /// </summary>
        internal static string TableRowByThreeParams {
            get {
                return ResourceManager.GetString("TableRowByThreeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;{0}&quot;)):has(td:contains(&quot;{1}&quot;)).
        /// </summary>
        internal static string TableRowByTwoParams {
            get {
                return ResourceManager.GetString("TableRowByTwoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Composer_HQ_App_1&quot;)):has(td:contains(&quot;Available&quot;)).
        /// </summary>
        internal static string TableRowComposerHqApp1Available {
            get {
                return ResourceManager.GetString("TableRowComposerHqApp1Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Composer_HQ_App_1&quot;)):has(td:contains(&quot;Deleted&quot;)).
        /// </summary>
        internal static string TableRowComposerHqApp1Deleted {
            get {
                return ResourceManager.GetString("TableRowComposerHqApp1Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Composer_HQ_App_1&quot;)):has(td:contains(&quot;Published&quot;)).
        /// </summary>
        internal static string TableRowComposerHqApp1Published {
            get {
                return ResourceManager.GetString("TableRowComposerHqApp1Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;App&quot;):contains(&quot;2&quot;)):has(td:contains(&quot;Available&quot;)).
        /// </summary>
        internal static string TableRowComposerHqApp2Available {
            get {
                return ResourceManager.GetString("TableRowComposerHqApp2Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Composer_VIPB_App&quot;)).
        /// </summary>
        internal static string TableRowComposerVipbApp {
            get {
                return ResourceManager.GetString("TableRowComposerVipbApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Composer_VIPB_App&quot;)):has(td:contains(&quot;New&quot;)).
        /// </summary>
        internal static string TableRowComposerVipbAppNew {
            get {
                return ResourceManager.GetString("TableRowComposerVipbAppNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td.vb-cell-created-by.
        /// </summary>
        internal static string TableRowCreatedBy {
            get {
                return ResourceManager.GetString("TableRowCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbody tr:has(td.vb-cell-title:contains(&quot;{0}&quot;)) td.vb-cell-device:visible.
        /// </summary>
        internal static string TableRowDeviceTypeByTitle {
            get {
                return ResourceManager.GetString("TableRowDeviceTypeByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Beacon&quot;)).
        /// </summary>
        internal static string TableRowIbeaconApp {
            get {
                return ResourceManager.GetString("TableRowIbeaconApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Beacon&quot;)):has(td:contains(&quot;New&quot;)).
        /// </summary>
        internal static string TableRowIbeaconAppNew {
            get {
                return ResourceManager.GetString("TableRowIbeaconAppNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Beacon&quot;)):has(td:contains(&quot;Published&quot;)).
        /// </summary>
        internal static string TableRowIbeaconAppPublished {
            get {
                return ResourceManager.GetString("TableRowIbeaconAppPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td.vb-cell-updated span.
        /// </summary>
        internal static string TableRowModified {
            get {
                return ResourceManager.GetString("TableRowModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Player&quot;)).
        /// </summary>
        internal static string TableRowPlayerApp {
            get {
                return ResourceManager.GetString("TableRowPlayerApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Player&quot;)):has(td:contains(&quot;Available&quot;)).
        /// </summary>
        internal static string TableRowPlayerAppAvailable {
            get {
                return ResourceManager.GetString("TableRowPlayerAppAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Player&quot;)):has(td:contains(&quot;Deleted&quot;)).
        /// </summary>
        internal static string TableRowPlayerAppDeleted {
            get {
                return ResourceManager.GetString("TableRowPlayerAppDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Player&quot;)):has(td:contains(&quot;New&quot;)).
        /// </summary>
        internal static string TableRowPlayerAppNew {
            get {
                return ResourceManager.GetString("TableRowPlayerAppNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;Player&quot;)):has(td:contains(&quot;Published&quot;)).
        /// </summary>
        internal static string TableRowPlayerAppPublished {
            get {
                return ResourceManager.GetString("TableRowPlayerAppPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) vb-app-list tbody tr:has(td.vb-row-selected):visible.
        /// </summary>
        internal static string TableRowSelected {
            get {
                return ResourceManager.GetString("TableRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td.vb-cell-status span.
        /// </summary>
        internal static string TableRowStatus {
            get {
                return ResourceManager.GetString("TableRowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(span.td-title:contains(&quot;{0}&quot;)) td.vb-cell-status span:visible.
        /// </summary>
        internal static string TableRowStatusByTitle {
            get {
                return ResourceManager.GetString("TableRowStatusByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td.vb-cell-title.
        /// </summary>
        internal static string TableRowTitle {
            get {
                return ResourceManager.GetString("TableRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) vb-app-list tbody tr:not(:has(td.vb-row-selected)):visible.
        /// </summary>
        internal static string TableRowUnselected {
            get {
                return ResourceManager.GetString("TableRowUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td:contains(&quot;{0}&quot;)):has(td:contains(&quot;{1}&quot;)).
        /// </summary>
        internal static string TableRowVersionStatus {
            get {
                return ResourceManager.GetString("TableRowVersionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-goodbye-message #inp-text textarea.
        /// </summary>
        internal static string TextInGoodByeMessage {
            get {
                return ResourceManager.GetString("TextInGoodByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-texts:visible.
        /// </summary>
        internal static string TextsButton {
            get {
                return ResourceManager.GetString("TextsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-texts div.vb-object-title div.
        /// </summary>
        internal static string TextsGroupCollapseButton {
            get {
                return ResourceManager.GetString("TextsGroupCollapseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #s-prop-title input:not([readonly]).
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th:contains(&quot;Title&quot;).
        /// </summary>
        internal static string TitleColumn {
            get {
                return ResourceManager.GetString("TitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) th:contains(&quot;Title&quot;).
        /// </summary>
        internal static string TitleColumnModal {
            get {
                return ResourceManager.GetString("TitleColumnModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #arr-details-addresses-2 #inp-title input:not([readonly]).
        /// </summary>
        internal static string TitleLine2 {
            get {
                return ResourceManager.GetString("TitleLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-title div[title].
        /// </summary>
        internal static string TitleReadOnly {
            get {
                return ResourceManager.GetString("TitleReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-touchpoint-01:visible.
        /// </summary>
        internal static string Touchpoint01Button {
            get {
                return ResourceManager.GetString("Touchpoint01Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #s-prop-tpcontent #btn-add:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentAddButton {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #arr-row-tpcontent-1:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentRow1 {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #arr-details-tpcontent-1 #drop-content-desc-position span.selection:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentRow1ContentDescPositionDropDown {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentRow1ContentDescPositionDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #arr-details-tpcontent-1 #s-prop-contentmedia div.img-holder img[src^=&quot;http&quot;]:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentRow1ContentMedia {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentRow1ContentMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #arr-details-tpcontent-1 #s-prop-contentmedia vb-button.vb-upload-btn:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentRow1ContentMediaUploadButton {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentRow1ContentMediaUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #arr-details-tpcontent-1 #s-prop-contentpreviewimage div.img-holder img[src^=&quot;http&quot;]:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentRow1PreviewImage {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentRow1PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #arr-details-tpcontent-1 #s-prop-contentpreviewimage vb-button.vb-upload-btn:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointContentRow1PreviewImageUploadButton {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointContentRow1PreviewImageUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #s-prop-tppreviewimage div.img-holder img[src^=&quot;http&quot;]:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointPreviewImage {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #s-prop-tppreviewimage vb-button.vb-upload-btn:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointPreviewImageUploadButton {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointPreviewImageUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #inp-touchpoint-title input:visible.
        /// </summary>
        internal static string Touchpoint01TouchpointTitle {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-01 #inp-touchpoint-title div[title].
        /// </summary>
        internal static string Touchpoint01TouchpointTitleReadOnly {
            get {
                return ResourceManager.GetString("Touchpoint01TouchpointTitleReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-touchpoint-02:visible.
        /// </summary>
        internal static string Touchpoint02Button {
            get {
                return ResourceManager.GetString("Touchpoint02Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-02 #arr-row-tpcontent-1:visible.
        /// </summary>
        internal static string Touchpoint02TouchpointContentRow1 {
            get {
                return ResourceManager.GetString("Touchpoint02TouchpointContentRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-02 #s-prop-tppreviewimage div.img-holder img[src^=&quot;http&quot;]:visible.
        /// </summary>
        internal static string Touchpoint02TouchpointPreviewImage {
            get {
                return ResourceManager.GetString("Touchpoint02TouchpointPreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-touchpoint-02 #s-prop-tppreviewimage vb-button.vb-upload-btn:visible.
        /// </summary>
        internal static string Touchpoint02TouchpointPreviewImageUploadButton {
            get {
                return ResourceManager.GetString("Touchpoint02TouchpointPreviewImageUploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-touchpoint-{0}:visible.
        /// </summary>
        internal static string TouchpointNButton {
            get {
                return ResourceManager.GetString("TouchpointNButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-button#btn-touchpoints:visible.
        /// </summary>
        internal static string TouchpointsButton {
            get {
                return ResourceManager.GetString("TouchpointsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-new-cars #inp-twitter textarea.
        /// </summary>
        internal static string TwitterInNewCars {
            get {
                return ResourceManager.GetString("TwitterInNewCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #obj-prop-sharing-templates-for-used-cars #inp-twitter textarea.
        /// </summary>
        internal static string TwitterInUsedCars {
            get {
                return ResourceManager.GetString("TwitterInUsedCars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        internal static string UnitForMileageKm {
            get {
                return ResourceManager.GetString("UnitForMileageKm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-unit-for-mileage-of-leasing [class~=&quot;select2&quot;].
        /// </summary>
        internal static string UnitForMileageOfLeasing {
            get {
                return ResourceManager.GetString("UnitForMileageOfLeasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-unit-for-mileage-of-leasing div.vb-form-input.
        /// </summary>
        internal static string UnitForMileageOfLeasingVal {
            get {
                return ResourceManager.GetString("UnitForMileageOfLeasingVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;Upload has been successfully completed&quot;).
        /// </summary>
        internal static string UploadHasBeenSuccessfullyCompletedDialog {
            get {
                return ResourceManager.GetString("UploadHasBeenSuccessfullyCompletedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #app-ver div.vb-app-list-ver:has(div.vb-control-label[hidden]) span.vb-app-ver:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #app-ver div.vb-app-inactive-ver a.
        /// </summary>
        internal static string VersionInactive {
            get {
                return ResourceManager.GetString("VersionInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #app-ver div.vb-app-list-ver:visible.
        /// </summary>
        internal static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #app-ver div.vb-app-inactive-ver.
        /// </summary>
        internal static string VersionsInactive {
            get {
                return ResourceManager.GetString("VersionsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-welcome-new-customer span.select2-selection:visible.
        /// </summary>
        internal static string WelcomeNewCustomer {
            get {
                return ResourceManager.GetString("WelcomeNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-welcome-new-customer span.vb-icon:visible.
        /// </summary>
        internal static string WelcomeNewCustomerDetailsButton {
            get {
                return ResourceManager.GetString("WelcomeNewCustomerDetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #drop-welcome-new-customer div[title].
        /// </summary>
        internal static string WelcomeNewCustomerReadOnly {
            get {
                return ResourceManager.GetString("WelcomeNewCustomerReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-wifi-name input:not([readonly]).
        /// </summary>
        internal static string WifiName {
            get {
                return ResourceManager.GetString("WifiName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-wifi-name div[title].
        /// </summary>
        internal static string WifiNameReadOnly {
            get {
                return ResourceManager.GetString("WifiNameReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;have corresponding permission&quot;).
        /// </summary>
        internal static string YouDontHaveCorrespondingPermissionDialog {
            get {
                return ResourceManager.GetString("YouDontHaveCorrespondingPermissionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;have permissions&quot;).
        /// </summary>
        internal static string YouDontHavePermissionsDialog {
            get {
                return ResourceManager.GetString("YouDontHavePermissionsDialog", resourceCulture);
            }
        }
    }
}
