//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Devices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Devices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.Devices", typeof(Devices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-footer #band-btn-add:visible.
        /// </summary>
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-agent-version div[title].
        /// </summary>
        internal static string AgentVersionReadOnly {
            get {
                return ResourceManager.GetString("AgentVersionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-footer #band-btn-cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal.vb-device-popup:not([hidden]) #band-btn-cancel.
        /// </summary>
        internal static string CancelButtonDevice {
            get {
                return ResourceManager.GetString("CancelButtonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-clear-selection.
        /// </summary>
        internal static string ClearSelectionButton {
            get {
                return ResourceManager.GetString("ClearSelectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal.vb-device-popup:not([hidden]) #band-btn-delete.
        /// </summary>
        internal static string DeleteButtonDevice {
            get {
                return ResourceManager.GetString("DeleteButtonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list:visible.
        /// </summary>
        internal static string DevicesDialog {
            get {
                return ResourceManager.GetString("DevicesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-major .vb-validation-msg:contains(&quot;required&quot;):visible.
        /// </summary>
        internal static string ErrorMajorRequired {
            get {
                return ResourceManager.GetString("ErrorMajorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-minor .vb-validation-msg:contains(&quot;required&quot;):visible.
        /// </summary>
        internal static string ErrorMinorRequired {
            get {
                return ResourceManager.GetString("ErrorMinorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-uuid .vb-validation-msg:contains(&quot;does not match&quot;):visible.
        /// </summary>
        internal static string ErrorUuidDoesNotMatchPattern {
            get {
                return ResourceManager.GetString("ErrorUuidDoesNotMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-uuid .vb-validation-msg:contains(&quot;required&quot;):visible.
        /// </summary>
        internal static string ErrorUuidRequired {
            get {
                return ResourceManager.GetString("ErrorUuidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-footer #band-btn-hide-deleted:visible.
        /// </summary>
        internal static string HideDeletedButton {
            get {
                return ResourceManager.GetString("HideDeletedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-major input:not([readonly]).
        /// </summary>
        internal static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-major div.vb-button:contains(&quot;+&quot;).
        /// </summary>
        internal static string MajorIncreaseButton {
            get {
                return ResourceManager.GetString("MajorIncreaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-major div.vb-form-input[title].
        /// </summary>
        internal static string MajorReadOnly {
            get {
                return ResourceManager.GetString("MajorReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-minor input:not([readonly]).
        /// </summary>
        internal static string Minor {
            get {
                return ResourceManager.GetString("Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #num-inp-minor div.vb-form-input[title].
        /// </summary>
        internal static string MinorReadOnly {
            get {
                return ResourceManager.GetString("MinorReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-pc-number div[title].
        /// </summary>
        internal static string PcNumberReadOnly {
            get {
                return ResourceManager.GetString("PcNumberReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-rack-number input:not([readonly]).
        /// </summary>
        internal static string RackNumber {
            get {
                return ResourceManager.GetString("RackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-rack-number div[title].
        /// </summary>
        internal static string RackNumberReadOnly {
            get {
                return ResourceManager.GetString("RackNumberReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal.vb-device-popup:not([hidden]) #band-btn-restore.
        /// </summary>
        internal static string RestoreButtonDevice {
            get {
                return ResourceManager.GetString("RestoreButtonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-footer #band-btn-show-deleted:visible.
        /// </summary>
        internal static string ShowDeletedButton {
            get {
                return ResourceManager.GetString("ShowDeletedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal.vb-device-popup:not([hidden]) #band-btn-submit.
        /// </summary>
        internal static string SubmitButtonDevice {
            get {
                return ResourceManager.GetString("SubmitButtonDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-table div.table-row:not(.table-header).
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-table div:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowByText {
            get {
                return ResourceManager.GetString("TableRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-table div[data-prop=&quot;name&quot;]:contains(&quot;{0}&quot;)+div[data-prop=&quot;attachmentPlaceTitle&quot;].
        /// </summary>
        internal static string TableRowPlaceByTitle {
            get {
                return ResourceManager.GetString("TableRowPlaceByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-table div.selected div[data-prop=&quot;name&quot;]:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowSelectedByTitle {
            get {
                return ResourceManager.GetString("TableRowSelectedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-table div.table-row:contains(&quot;{0}&quot;)&gt;div[data-prop=&quot;status&quot;].
        /// </summary>
        internal static string TableRowStatusByTitle {
            get {
                return ResourceManager.GetString("TableRowStatusByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-devices-list vb-table div:not(.table-header) div[data-prop=&quot;name&quot;].
        /// </summary>
        internal static string TableRowTitle {
            get {
                return ResourceManager.GetString("TableRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-uuid input:visible.
        /// </summary>
        internal static string Uuid {
            get {
                return ResourceManager.GetString("Uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-uuid div[title].
        /// </summary>
        internal static string UuidReadOnly {
            get {
                return ResourceManager.GetString("UuidReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #inp-vpn-ip div[title].
        /// </summary>
        internal static string VpnIpReadOnly {
            get {
                return ResourceManager.GetString("VpnIpReadOnly", resourceCulture);
            }
        }
    }
}
