//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExportImport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportImport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.ExportImport", typeof(ExportImport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #div-pl-sub-menu:visible.
        /// </summary>
        internal static string AddSubMenu {
            get {
                return ResourceManager.GetString("AddSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-import-filter span:contains(&quot;All&quot;):visible.
        /// </summary>
        internal static string AllTab {
            get {
                return ResourceManager.GetString("AllTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Import completed&quot;)) div.vb-import-filter span:contains(&quot;All&quot;):visible.
        /// </summary>
        internal static string AllTabCompleted {
            get {
                return ResourceManager.GetString("AllTabCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-sub-items #band-btn-apps:visible.
        /// </summary>
        internal static string AppsButton {
            get {
                return ResourceManager.GetString("AppsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-import-filter span:contains(&quot;Apps&quot;):visible.
        /// </summary>
        internal static string AppsTab {
            get {
                return ResourceManager.GetString("AppsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Import completed&quot;)) div.vb-import-filter span:contains(&quot;Apps&quot;):visible.
        /// </summary>
        internal static string AppsTabCompleted {
            get {
                return ResourceManager.GetString("AppsTabCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #band-btn-cancel:visible.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #band-btn-clear-all[ng-reflect-disabled!=&quot;true&quot;]:visible.
        /// </summary>
        internal static string ClearAllButton {
            get {
                return ResourceManager.GetString("ClearAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #band-btn-clear-all[ng-reflect-disabled=&quot;true&quot;]:visible.
        /// </summary>
        internal static string ClearAllButtonDisabled {
            get {
                return ResourceManager.GetString("ClearAllButtonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-import-export vb-footer #band-btn-close.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)):visible.
        /// </summary>
        internal static string Dialog {
            get {
                return ResourceManager.GetString("Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:contains(&quot;archive doesn\&apos;t contain tenant data&quot;):visible.
        /// </summary>
        internal static string ErrorArchiveDoesNotContainTenantData {
            get {
                return ResourceManager.GetString("ErrorArchiveDoesNotContainTenantData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #band-btn-export[ng-reflect-disabled!=&quot;true&quot;]:visible.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #band-btn-export[ng-reflect-disabled=&quot;true&quot;]:visible.
        /// </summary>
        internal static string ExportButtonDisabled {
            get {
                return ResourceManager.GetString("ExportButtonDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) #band-btn-import:visible.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-import-export h1:contains(&quot;Import completed&quot;):visible.
        /// </summary>
        internal static string ImportCompletedDialog {
            get {
                return ResourceManager.GetString("ImportCompletedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-sub-items #band-btn-items:visible.
        /// </summary>
        internal static string ItemsButton {
            get {
                return ResourceManager.GetString("ItemsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-import-filter span:contains(&quot;Items&quot;):visible.
        /// </summary>
        internal static string ItemsTab {
            get {
                return ResourceManager.GetString("ItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Import completed&quot;)) div.vb-import-filter span:contains(&quot;Items&quot;):visible.
        /// </summary>
        internal static string ItemsTabCompleted {
            get {
                return ResourceManager.GetString("ItemsTabCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal #band-btn-no.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal #band-btn-ok:visible.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-sub-items #band-btn-places:visible.
        /// </summary>
        internal static string PlacesButton {
            get {
                return ResourceManager.GetString("PlacesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) div.vb-import-filter span:contains(&quot;Places&quot;):visible.
        /// </summary>
        internal static string PlacesTab {
            get {
                return ResourceManager.GetString("PlacesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Import completed&quot;)) div.vb-import-filter span:contains(&quot;Places&quot;):visible.
        /// </summary>
        internal static string PlacesTabCompleted {
            get {
                return ResourceManager.GetString("PlacesTabCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.vb-modal-content:contains(&quot;page is to be refreshed&quot;):visible.
        /// </summary>
        internal static string RefreshPageDialog {
            get {
                return ResourceManager.GetString("RefreshPageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) vb-table div.table-row:not(.table-header).
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) vb-table div.table-row:contains(&quot;{0}&quot;).
        /// </summary>
        internal static string TableRowByText {
            get {
                return ResourceManager.GetString("TableRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) vb-table div.table-row:not(.table-header) div[data-prop=&quot;title&quot;]:visible.
        /// </summary>
        internal static string TableRowTitle {
            get {
                return ResourceManager.GetString("TableRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Import completed&quot;)) vb-table div.table-row:not(.table-header) div[data-prop=&quot;title&quot;]:visible.
        /// </summary>
        internal static string TableRowTitleCompleted {
            get {
                return ResourceManager.GetString("TableRowTitleCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:has(h1:contains(&quot;Export/Import&quot;)) vb-table div.table-row:not(.table-header) div[data-prop=&quot;dispType&quot;]:visible.
        /// </summary>
        internal static string TableRowType {
            get {
                return ResourceManager.GetString("TableRowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal #band-btn-yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
