//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoginPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.LoginPage", typeof(LoginPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-cancel:visible.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-close:visible.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div:contains(&quot;don\&apos;t have access to this tenant&quot;):visible.
        /// </summary>
        internal static string DontHaveAccessToThisTenant {
            get {
                return ResourceManager.GetString("DontHaveAccessToThisTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Your account hasn\&apos;t been activated yet&quot;):visible.
        /// </summary>
        internal static string ErrorAccountHasNotBeenActivated {
            get {
                return ResourceManager.GetString("ErrorAccountHasNotBeenActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Due to 3 wrong password attempts, your account has been locked for&quot;):visible.
        /// </summary>
        internal static string ErrorAccountLocked {
            get {
                return ResourceManager.GetString("ErrorAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Email doesn\&apos;t match pattern&quot;):visible.
        /// </summary>
        internal static string ErrorEmailDoesntMatch {
            get {
                return ResourceManager.GetString("ErrorEmailDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Email is required&quot;):visible.
        /// </summary>
        internal static string ErrorEmailIsRequired {
            get {
                return ResourceManager.GetString("ErrorEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-errors-list ul:visible.
        /// </summary>
        internal static string ErrorMessagePlaceholder {
            get {
                return ResourceManager.GetString("ErrorMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;permissions assigned to&quot;):visible.
        /// </summary>
        internal static string ErrorNoRolesAndPermissionsAssigned {
            get {
                return ResourceManager.GetString("ErrorNoRolesAndPermissionsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div:contains(&quot;access the system&quot;):visible.
        /// </summary>
        internal static string ErrorNotAuthorizedToAccessSystem {
            get {
                return ResourceManager.GetString("ErrorNotAuthorizedToAccessSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Password is required&quot;):visible.
        /// </summary>
        internal static string ErrorPasswordIsRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;User does not exist or password did not match&quot;):visible.
        /// </summary>
        internal static string ErrorWrongUserOrPassword {
            get {
                return ResourceManager.GetString("ErrorWrongUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-forgot-password:visible.
        /// </summary>
        internal static string ForgotPasswordButton {
            get {
                return ResourceManager.GetString("ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-login:not(.vb-disabled):visible.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#email:visible.
        /// </summary>
        internal static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#password:visible.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form div.vb-modal-content img:visible.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-ok:visible.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-register:not(.vb-disabled):visible.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-request-access:visible.
        /// </summary>
        internal static string RequestAccessButton {
            get {
                return ResourceManager.GetString("RequestAccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div:contains(&quot;for another CX Manager application&quot;):visible.
        /// </summary>
        internal static string RequestAccessToCxmWindow {
            get {
                return ResourceManager.GetString("RequestAccessToCxmWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div:contains(&quot;Your request has been sent&quot;):visible.
        /// </summary>
        internal static string RequestSentWindow {
            get {
                return ResourceManager.GetString("RequestSentWindow", resourceCulture);
            }
        }
    }
}
