//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MediaLibrary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MediaLibrary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.MediaLibrary", typeof(MediaLibrary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-cancel:visible.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-close:visible.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-copy-url:visible.
        /// </summary>
        internal static string CopyUrlButton {
            get {
                return ResourceManager.GetString("CopyUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library span.header-text:contains(&quot;Created&quot;).
        /// </summary>
        internal static string CreatedColumn {
            get {
                return ResourceManager.GetString("CreatedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-crop:visible.
        /// </summary>
        internal static string CropButton {
            get {
                return ResourceManager.GetString("CropButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-deselect-all:visible.
        /// </summary>
        internal static string DeselectAllButton {
            get {
                return ResourceManager.GetString("DeselectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-distribute:not(.vb-disabled):visible.
        /// </summary>
        internal static string DistributeButton {
            get {
                return ResourceManager.GetString("DistributeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-distribute.vb-disabled:visible.
        /// </summary>
        internal static string DistributeButtonInactive {
            get {
                return ResourceManager.GetString("DistributeButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-download:visible.
        /// </summary>
        internal static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal .vb-modal-content:contains(&quot;format is not supported&quot;):visible.
        /// </summary>
        internal static string ErrorFormatIsNotSupportedDialog {
            get {
                return ResourceManager.GetString("ErrorFormatIsNotSupportedDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-expiry-date:visible.
        /// </summary>
        internal static string ExpiryDateButton {
            get {
                return ResourceManager.GetString("ExpiryDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-select input.vb-band-input:visible.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-select span.selection:visible.
        /// </summary>
        internal static string FilterDropDown {
            get {
                return ResourceManager.GetString("FilterDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library:visible.
        /// </summary>
        internal static string MediaLibraryDialog {
            get {
                return ResourceManager.GetString("MediaLibraryDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div#band-btn-modify:visible.
        /// </summary>
        internal static string ModifySubMenu {
            get {
                return ResourceManager.GetString("ModifySubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.vb-ml-thumb:not(.vb-ml-thumb-selected).
        /// </summary>
        internal static string NotSelectedImage {
            get {
                return ResourceManager.GetString("NotSelectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-resize:visible.
        /// </summary>
        internal static string ResizeButton {
            get {
                return ResourceManager.GetString("ResizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-select-all:visible.
        /// </summary>
        internal static string SelectAllButton {
            get {
                return ResourceManager.GetString("SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.vb-ml-preview img:visible.
        /// </summary>
        internal static string SelectedImageZoomed {
            get {
                return ResourceManager.GetString("SelectedImageZoomed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div#band-btn-share:visible.
        /// </summary>
        internal static string ShareSubMenu {
            get {
                return ResourceManager.GetString("ShareSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library span.header-text:contains(&quot;Size&quot;).
        /// </summary>
        internal static string SizeColumn {
            get {
                return ResourceManager.GetString("SizeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:contains(&quot;{0}&quot;) div[data-prop=&quot;title&quot;]:visible.
        /// </summary>
        internal static string TableRowByText {
            get {
                return ResourceManager.GetString("TableRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:has(div[data-prop=&quot;title&quot;]:contains(&quot;{0}&quot;)) div[data-prop=&quot;sCreated&quot;]:visible.
        /// </summary>
        internal static string TableRowCreatedByTitle {
            get {
                return ResourceManager.GetString("TableRowCreatedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:not(.selected):not(.table-header):visible.
        /// </summary>
        internal static string TableRowNotSelected {
            get {
                return ResourceManager.GetString("TableRowNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:not(.selected):not(.table-header):contains(&quot;{0}&quot;).
        /// </summary>
        internal static string TableRowNotSelectedByText {
            get {
                return ResourceManager.GetString("TableRowNotSelectedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row div[data-prop=&quot;thumbUrl&quot;]:visible.
        /// </summary>
        internal static string TableRowPicture {
            get {
                return ResourceManager.GetString("TableRowPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:not(.table-header) div[data-prop=&quot;title&quot;]:visible.
        /// </summary>
        internal static string TableRows {
            get {
                return ResourceManager.GetString("TableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row.selected:visible.
        /// </summary>
        internal static string TableRowSelected {
            get {
                return ResourceManager.GetString("TableRowSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row.selected:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowSelectedByText {
            get {
                return ResourceManager.GetString("TableRowSelectedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:has(div[data-prop=&quot;title&quot;]:contains(&quot;{0}&quot;)) div[data-prop=&quot;size&quot;]:visible.
        /// </summary>
        internal static string TableRowSizeByTitle {
            get {
                return ResourceManager.GetString("TableRowSizeByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:has(div[data-prop=&quot;type&quot;]:contains(&quot;{0}&quot;)) div[data-prop=&quot;size&quot;]:visible.
        /// </summary>
        internal static string TableRowSizeByType {
            get {
                return ResourceManager.GetString("TableRowSizeByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library div.table-row:has(div[data-prop=&quot;title&quot;]:contains(&quot;{0}&quot;)) div[data-prop=&quot;type&quot;]:visible.
        /// </summary>
        internal static string TableRowTypeByTitle {
            get {
                return ResourceManager.GetString("TableRowTypeByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-tags:visible.
        /// </summary>
        internal static string TagsButton {
            get {
                return ResourceManager.GetString("TagsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library span.header-text:contains(&quot;Title&quot;).
        /// </summary>
        internal static string TitleColumn {
            get {
                return ResourceManager.GetString("TitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library span.header-text:contains(&quot;Type&quot;).
        /// </summary>
        internal static string TypeColumn {
            get {
                return ResourceManager.GetString("TypeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library vb-band-button#band-btn-upload:not(.vb-disabled):visible.
        /// </summary>
        internal static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-media-library video[autoplay]:visible.
        /// </summary>
        internal static string VideoPlayerStarted {
            get {
                return ResourceManager.GetString("VideoPlayerStarted", resourceCulture);
            }
        }
    }
}
