//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageFooter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageFooter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.PageFooter", typeof(PageFooter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-add-new[par-screen=&quot;app-list&quot;]:visible.
        /// </summary>
        internal static string AddAppInAppsButton {
            get {
                return ResourceManager.GetString("AddAppInAppsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-add-app:visible.
        /// </summary>
        internal static string AddAppInPlacesButton {
            get {
                return ResourceManager.GetString("AddAppInPlacesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-add-existing-place-as-child:visible.
        /// </summary>
        internal static string AddExistingPlaceAsChildButton {
            get {
                return ResourceManager.GetString("AddExistingPlaceAsChildButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-add-new[par-screen=&quot;item-list&quot;]:visible.
        /// </summary>
        internal static string AddItemButton {
            get {
                return ResourceManager.GetString("AddItemButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-add-new[par-screen=&quot;place-list&quot;]:visible.
        /// </summary>
        internal static string AddPlaceButton {
            get {
                return ResourceManager.GetString("AddPlaceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#div-pl-sub-menu:visible.
        /// </summary>
        internal static string AddPlaceSubMenu {
            get {
                return ResourceManager.GetString("AddPlaceSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#div-pl-sub-menu.vb-disabled:visible.
        /// </summary>
        internal static string AddPlaceSubMenuInactive {
            get {
                return ResourceManager.GetString("AddPlaceSubMenuInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-add-version:visible.
        /// </summary>
        internal static string AddVersionButton {
            get {
                return ResourceManager.GetString("AddVersionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-apps-order:visible.
        /// </summary>
        internal static string AppsOrderButton {
            get {
                return ResourceManager.GetString("AppsOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-cancel:visible.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-clear-selection:visible.
        /// </summary>
        internal static string ClearSelectionButton {
            get {
                return ResourceManager.GetString("ClearSelectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-close:visible.
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-copy-url:visible.
        /// </summary>
        internal static string CopyUrlButton {
            get {
                return ResourceManager.GetString("CopyUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-create-new-child-place:visible.
        /// </summary>
        internal static string CreateNewChildPlaceButton {
            get {
                return ResourceManager.GetString("CreateNewChildPlaceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-delete:visible.
        /// </summary>
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#div-pl-sub-menu-distr #sub-menu-app-distr:visible.
        /// </summary>
        internal static string DistributeAppButton {
            get {
                return ResourceManager.GetString("DistributeAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-distribute:not(.vb-disabled):visible.
        /// </summary>
        internal static string DistributeButton {
            get {
                return ResourceManager.GetString("DistributeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#div-pl-sub-menu-distr #sub-menu-master-distr:visible.
        /// </summary>
        internal static string DistributeMasterDataButton {
            get {
                return ResourceManager.GetString("DistributeMasterDataButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#div-pl-sub-menu-distr:visible.
        /// </summary>
        internal static string DistributeSubMenu {
            get {
                return ResourceManager.GetString("DistributeSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-download:visible.
        /// </summary>
        internal static string DownloadButton {
            get {
                return ResourceManager.GetString("DownloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-duplicate:visible.
        /// </summary>
        internal static string DuplicateButton {
            get {
                return ResourceManager.GetString("DuplicateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-duplicate.vb-disabled.
        /// </summary>
        internal static string DuplicateButtonInactive {
            get {
                return ResourceManager.GetString("DuplicateButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-edit:visible.
        /// </summary>
        internal static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-file-access:visible.
        /// </summary>
        internal static string FileAccessButton {
            get {
                return ResourceManager.GetString("FileAccessButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-file-access.vb-disabled:visible.
        /// </summary>
        internal static string FileAccessButtonInactive {
            get {
                return ResourceManager.GetString("FileAccessButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button[el-id*=&quot;btn-followd&quot;]:visible.
        /// </summary>
        internal static string FollowButton {
            get {
                return ResourceManager.GetString("FollowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button[el-id*=&quot;btn-followd&quot;].vb-disabled:visible.
        /// </summary>
        internal static string FollowButtonInactive {
            get {
                return ResourceManager.GetString("FollowButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button[el-id*=&quot;btn-hide-deleted&quot;]:visible.
        /// </summary>
        internal static string HideDeletedButton {
            get {
                return ResourceManager.GetString("HideDeletedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-import:visible.
        /// </summary>
        internal static string ImportButton {
            get {
                return ResourceManager.GetString("ImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#div-pl-sub-menu:visible.
        /// </summary>
        internal static string ImportSubMenu {
            get {
                return ResourceManager.GetString("ImportSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-live-images:visible.
        /// </summary>
        internal static string LiveImagesButton {
            get {
                return ResourceManager.GetString("LiveImagesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-live-images.vb-disabled:visible.
        /// </summary>
        internal static string LiveImagesButtonInactive {
            get {
                return ResourceManager.GetString("LiveImagesButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#band-btn-modify:visible.
        /// </summary>
        internal static string ModifySubMenu {
            get {
                return ResourceManager.GetString("ModifySubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-porsche-car:visible.
        /// </summary>
        internal static string PorscheCarButton {
            get {
                return ResourceManager.GetString("PorscheCarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-properties-order:visible.
        /// </summary>
        internal static string PropertiesOrderButton {
            get {
                return ResourceManager.GetString("PropertiesOrderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-push:visible.
        /// </summary>
        internal static string PushButton {
            get {
                return ResourceManager.GetString("PushButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-request-approval:visble.
        /// </summary>
        internal static string RequestApprovalButton {
            get {
                return ResourceManager.GetString("RequestApprovalButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-restore:visible.
        /// </summary>
        internal static string RestoreButton {
            get {
                return ResourceManager.GetString("RestoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-select:visible.
        /// </summary>
        internal static string SelectButton {
            get {
                return ResourceManager.GetString("SelectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer div#band-btn-share:visible.
        /// </summary>
        internal static string ShareSubMenu {
            get {
                return ResourceManager.GetString("ShareSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button[el-id*=&quot;btn-show-deleted&quot;]:visible.
        /// </summary>
        internal static string ShowDeletedButton {
            get {
                return ResourceManager.GetString("ShowDeletedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-submit:visible.
        /// </summary>
        internal static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button[el-id*=&quot;btn-unfollowd&quot;]:visible.
        /// </summary>
        internal static string UnfollowButton {
            get {
                return ResourceManager.GetString("UnfollowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-upload:visible.
        /// </summary>
        internal static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-footer vb-band-button#band-btn-upload-day:visible.
        /// </summary>
        internal static string UploadDayButton {
            get {
                return ResourceManager.GetString("UploadDayButton", resourceCulture);
            }
        }
    }
}
