//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PageHeader {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageHeader() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.PageHeader", typeof(PageHeader).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-header vb-filter vb-band-button:visible.
        /// </summary>
        internal static string AdvancedFilterButton {
            get {
                return ResourceManager.GetString("AdvancedFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-header vb-filter vb-band-button.vb-band-button__active:visible.
        /// </summary>
        internal static string AdvancedFilterButtonActive {
            get {
                return ResourceManager.GetString("AdvancedFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-breadcrumb span[class~=&quot;vb-tenant&quot;]:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string BreadCrumb {
            get {
                return ResourceManager.GetString("BreadCrumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-breadcrumb span.vb-tenant.
        /// </summary>
        internal static string BreadCrumbsAllPath {
            get {
                return ResourceManager.GetString("BreadCrumbsAllPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-breadcrumb:visible.
        /// </summary>
        internal static string BreadCrumbsWebElement {
            get {
                return ResourceManager.GetString("BreadCrumbsWebElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-breadcrumb:visible span:contains(&quot;Tenants&quot;):visible.
        /// </summary>
        internal static string BreadCrumbTenants {
            get {
                return ResourceManager.GetString("BreadCrumbTenants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #band-btn-cancel-all-tasks:visible.
        /// </summary>
        internal static string CancelAllTasksButton {
            get {
                return ResourceManager.GetString("CancelAllTasksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li.select2-results__option:visible:has(img).
        /// </summary>
        internal static string DropDownOptionListWithIcons {
            get {
                return ResourceManager.GetString("DropDownOptionListWithIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div.vb-modal-content:contains(&quot;You have selected wrong package&quot;):visible.
        /// </summary>
        internal static string ErrorYouHaveSelectedWrongPackageDialog {
            get {
                return ResourceManager.GetString("ErrorYouHaveSelectedWrongPackageDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-header vb-filter input.vb-band-input:visible.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-header vb-filter span.selection:visible.
        /// </summary>
        internal static string FilterDropDown {
            get {
                return ResourceManager.GetString("FilterDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span.select2-selection__rendered.
        /// </summary>
        internal static string FilterDropDownValue {
            get {
                return ResourceManager.GetString("FilterDropDownValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-header vb-band-button[class~=&quot;vb-btn-back&quot;].
        /// </summary>
        internal static string NavigateBackButton {
            get {
                return ResourceManager.GetString("NavigateBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Apps&quot;):visible.
        /// </summary>
        internal static string PageAppsButton {
            get {
                return ResourceManager.GetString("PageAppsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Cars&quot;):visible.
        /// </summary>
        internal static string PageCarsButton {
            get {
                return ResourceManager.GetString("PageCarsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Email template&quot;):visible.
        /// </summary>
        internal static string PageEmailTemplateButton {
            get {
                return ResourceManager.GetString("PageEmailTemplateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Items&quot;):visible.
        /// </summary>
        internal static string PageItemsButton {
            get {
                return ResourceManager.GetString("PageItemsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Media&quot;):visible.
        /// </summary>
        internal static string PageMediaButton {
            get {
                return ResourceManager.GetString("PageMediaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-header .vb-title div:visible.
        /// </summary>
        internal static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Places&quot;):visible.
        /// </summary>
        internal static string PagePlacesButton {
            get {
                return ResourceManager.GetString("PagePlacesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-tab:contains(&quot;Porsche Car&quot;):visible.
        /// </summary>
        internal static string PagePorscheCarButton {
            get {
                return ResourceManager.GetString("PagePorscheCarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list:visible.
        /// </summary>
        internal static string TasksDialog {
            get {
                return ResourceManager.GetString("TasksDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:has(div.vb-up-percent):contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TasksTableRowByText {
            get {
                return ResourceManager.GetString("TasksTableRowByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:contains(&quot;{0}&quot;) vb-button[title=&quot;Delete&quot;]:visible.
        /// </summary>
        internal static string TasksTableRowByTextDeleteButton {
            get {
                return ResourceManager.GetString("TasksTableRowByTextDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:contains(&quot;{0}&quot;) div.vb-up-percent:visible.
        /// </summary>
        internal static string TasksTableRowByTextPercentage {
            get {
                return ResourceManager.GetString("TasksTableRowByTextPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:contains(&quot;{0}&quot;) div.vb-up-status-progress.vb-task-fail:visible.
        /// </summary>
        internal static string TasksTableRowByTextProgressFailed {
            get {
                return ResourceManager.GetString("TasksTableRowByTextProgressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:contains(&quot;{0}&quot;) vb-button[title=&quot;Re-upload&quot;]:visible.
        /// </summary>
        internal static string TasksTableRowByTextReuploadButton {
            get {
                return ResourceManager.GetString("TasksTableRowByTextReuploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:contains(&quot;{0}&quot;):contains(&quot;{1}&quot;):contains(&quot;{2}&quot;).
        /// </summary>
        internal static string TasksTableRowByThreeParams {
            get {
                return ResourceManager.GetString("TasksTableRowByThreeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-task-list div.vb-arr-row:contains(&quot;{0}&quot;):contains(&quot;{1}&quot;).
        /// </summary>
        internal static string TasksTableRowByTwoParams {
            get {
                return ResourceManager.GetString("TasksTableRowByTwoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-spin-container div.vb-upload-spinner:visible.
        /// </summary>
        internal static string UploadSpinner {
            get {
                return ResourceManager.GetString("UploadSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-spin-container span.vb-spin-warn:visible.
        /// </summary>
        internal static string UploadWarning {
            get {
                return ResourceManager.GetString("UploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-user div.vb-user-menu:visible.
        /// </summary>
        internal static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-account:visible.
        /// </summary>
        internal static string UserMenuAccountButton {
            get {
                return ResourceManager.GetString("UserMenuAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-user:visible.
        /// </summary>
        internal static string UserMenuButton {
            get {
                return ResourceManager.GetString("UserMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-devices:visible.
        /// </summary>
        internal static string UserMenuDevicesButton {
            get {
                return ResourceManager.GetString("UserMenuDevicesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-export-import:visible.
        /// </summary>
        internal static string UserMenuExportImportButton {
            get {
                return ResourceManager.GetString("UserMenuExportImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-logout:visible.
        /// </summary>
        internal static string UserMenuLogoutButton {
            get {
                return ResourceManager.GetString("UserMenuLogoutButton", resourceCulture);
            }
        }
    }
}
