//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistrationPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.RegistrationPage", typeof(RegistrationPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-form-checkbox:has(input#acceptTerms).
        /// </summary>
        internal static string AcceptTermsCheckBox {
            get {
                return ResourceManager.GetString("AcceptTermsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-modal-content vb-terms-msg.
        /// </summary>
        internal static string AcceptTermsDialog {
            get {
                return ResourceManager.GetString("AcceptTermsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form a.
        /// </summary>
        internal static string AcceptTermsLink {
            get {
                return ResourceManager.GetString("AcceptTermsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;check your inbox to confirm&quot;):visible.
        /// </summary>
        internal static string CheckYourInboxDialog {
            get {
                return ResourceManager.GetString("CheckYourInboxDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[name=&quot;company&quot;].
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;confirm&quot;):visible.
        /// </summary>
        internal static string ConfirmRegistrationDialog {
            get {
                return ResourceManager.GetString("ConfirmRegistrationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[name=&quot;email&quot;].
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Please accept terms&quot;).
        /// </summary>
        internal static string ErrorAcceptTerms {
            get {
                return ResourceManager.GetString("ErrorAcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Your account hasn\&apos;t been activated yet&quot;).
        /// </summary>
        internal static string ErrorAccountHasNotBeenActivated {
            get {
                return ResourceManager.GetString("ErrorAccountHasNotBeenActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Company is required&quot;).
        /// </summary>
        internal static string ErrorCompanyIsRequired {
            get {
                return ResourceManager.GetString("ErrorCompanyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Company min length&quot;).
        /// </summary>
        internal static string ErrorCompanyMinLength {
            get {
                return ResourceManager.GetString("ErrorCompanyMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Email doesn\&apos;t match pattern&quot;).
        /// </summary>
        internal static string ErrorEmailDoesntMatch {
            get {
                return ResourceManager.GetString("ErrorEmailDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Email is required&quot;).
        /// </summary>
        internal static string ErrorEmailIsRequired {
            get {
                return ResourceManager.GetString("ErrorEmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;First Name is required&quot;).
        /// </summary>
        internal static string ErrorFirstNameIsRequired {
            get {
                return ResourceManager.GetString("ErrorFirstNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;First Name min length&quot;).
        /// </summary>
        internal static string ErrorFirstNameMinLength {
            get {
                return ResourceManager.GetString("ErrorFirstNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Last Name is required&quot;).
        /// </summary>
        internal static string ErrorLastNameIsRequired {
            get {
                return ResourceManager.GetString("ErrorLastNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Last Name min length&quot;).
        /// </summary>
        internal static string ErrorLastNameMinLength {
            get {
                return ResourceManager.GetString("ErrorLastNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-errors-list ul.
        /// </summary>
        internal static string ErrorMessagePlaceholder {
            get {
                return ResourceManager.GetString("ErrorMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Entered password is blacklisted&quot;).
        /// </summary>
        internal static string ErrorPasswordBlacklisted {
            get {
                return ResourceManager.GetString("ErrorPasswordBlacklisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Password is required&quot;).
        /// </summary>
        internal static string ErrorPasswordIsRequired {
            get {
                return ResourceManager.GetString("ErrorPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Password min length&quot;).
        /// </summary>
        internal static string ErrorPasswordMinLength {
            get {
                return ResourceManager.GetString("ErrorPasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Password max length&quot;).
        /// </summary>
        internal static string ErrorPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Phone doesn\&apos;t match pattern&quot;).
        /// </summary>
        internal static string ErrorPhoneDoesntMatch {
            get {
                return ResourceManager.GetString("ErrorPhoneDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Phone is required&quot;).
        /// </summary>
        internal static string ErrorPhoneIsRequired {
            get {
                return ResourceManager.GetString("ErrorPhoneIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Phone max length&quot;).
        /// </summary>
        internal static string ErrorPhoneMaxLength {
            get {
                return ResourceManager.GetString("ErrorPhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Phone min length&quot;).
        /// </summary>
        internal static string ErrorPhoneMinLength {
            get {
                return ResourceManager.GetString("ErrorPhoneMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;Repeat Password is required&quot;).
        /// </summary>
        internal static string ErrorRepeatPasswordIsRequired {
            get {
                return ResourceManager.GetString("ErrorRepeatPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;User does not exist or password did not match&quot;).
        /// </summary>
        internal static string ErrorWrongUserOrPassword {
            get {
                return ResourceManager.GetString("ErrorWrongUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li:contains(&quot;You already have an active account associated with this email&quot;).
        /// </summary>
        internal static string ErrorYourAlreadyHaveAnActiveAccount {
            get {
                return ResourceManager.GetString("ErrorYourAlreadyHaveAnActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[name=&quot;gname&quot;].
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[name=&quot;fname&quot;].
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to form div.vb-modal-content img.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-ok:visible.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[formcontrolname=&quot;txtPassword&quot;].
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[name=&quot;phone&quot;].
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-band-button#band-btn-register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input[formcontrolname=&quot;txtPasswordVerify&quot;].
        /// </summary>
        internal static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
    }
}
