//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TenantsPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenantsPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.TenantsPage", typeof(TenantsPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-band-button#band-btn-apply:not(.vb-disabled).
        /// </summary>
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-band-button#band-btn-apply.vb-disabled.
        /// </summary>
        internal static string ApplyDisabledButton {
            get {
                return ResourceManager.GetString("ApplyDisabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr td.vb-cell-hierarchy-title span[parent-title=&quot;{0}&quot;]:visible.
        /// </summary>
        internal static string ChildrenByParentTitle {
            get {
                return ResourceManager.GetString("ChildrenByParentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tr:has(td:contains(&quot;{0}&quot;)) div.ident-parent.
        /// </summary>
        internal static string CollapseExpandButton {
            get {
                return ResourceManager.GetString("CollapseExpandButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-deselect-all.
        /// </summary>
        internal static string DeselectAllButton {
            get {
                return ResourceManager.GetString("DeselectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-ok.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) #band-btn-select-all.
        /// </summary>
        internal static string SelectAllButton {
            get {
                return ResourceManager.GetString("SelectAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr:has(td.dataTables_empty).
        /// </summary>
        internal static string TableEmpty {
            get {
                return ResourceManager.GetString("TableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list th:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableHeaderByName {
            get {
                return ResourceManager.GetString("TableHeaderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr:first.
        /// </summary>
        internal static string TableRow1 {
            get {
                return ResourceManager.GetString("TableRow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr:first td.column-created-by:visible.
        /// </summary>
        internal static string TableRow1CreatedBy {
            get {
                return ResourceManager.GetString("TableRow1CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr:first td.column-tenant-code:visible.
        /// </summary>
        internal static string TableRow1TenantCode {
            get {
                return ResourceManager.GetString("TableRow1TenantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr:first td.vb-cell-hierarchy-title:visible.
        /// </summary>
        internal static string TableRow1Title {
            get {
                return ResourceManager.GetString("TableRow1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list td.column-tenant-code:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowByTenantCode {
            get {
                return ResourceManager.GetString("TableRowByTenantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list td.vb-cell-hierarchy-title:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowByTitle {
            get {
                return ResourceManager.GetString("TableRowByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr td.column-created-by:visible.
        /// </summary>
        internal static string TableRowCreatedBy {
            get {
                return ResourceManager.GetString("TableRowCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tr.disabled-row td.vb-cell-hierarchy-title:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowDisabledByTitle {
            get {
                return ResourceManager.GetString("TableRowDisabledByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr td.column-modified:visible.
        /// </summary>
        internal static string TableRowModified {
            get {
                return ResourceManager.GetString("TableRowModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list td.vb-row-selected.vb-cell-hierarchy-title:contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowSelectedByTitle {
            get {
                return ResourceManager.GetString("TableRowSelectedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr td.column-tenant-code:visible.
        /// </summary>
        internal static string TableRowTenantCode {
            get {
                return ResourceManager.GetString("TableRowTenantCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tbody tr td.vb-cell-hierarchy-title:visible.
        /// </summary>
        internal static string TableRowTitle {
            get {
                return ResourceManager.GetString("TableRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list td.vb-cell-hierarchy-title:not(.vb-row-selected):contains(&quot;{0}&quot;):visible.
        /// </summary>
        internal static string TableRowUnselectedByTitle {
            get {
                return ResourceManager.GetString("TableRowUnselectedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tr:not(.disabled-row) td.vb-cell-hierarchy-title:visible.
        /// </summary>
        internal static string TenantButton {
            get {
                return ResourceManager.GetString("TenantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tr[class*=&quot;hide-children&quot;]:has(td:contains(&quot;{0}&quot;)).
        /// </summary>
        internal static string TenantRowCollapsed {
            get {
                return ResourceManager.GetString("TenantRowCollapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-tenants-list tr:not([class*=&quot;hide-children&quot;]):has(td:contains(&quot;{0}&quot;)).
        /// </summary>
        internal static string TenantRowExpanded {
            get {
                return ResourceManager.GetString("TenantRowExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal h1:contains(&quot;Tenants&quot;):visible.
        /// </summary>
        internal static string TenantsDialog {
            get {
                return ResourceManager.GetString("TenantsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) vb-band-button#band-btn-upload:not(.vb-disabled).
        /// </summary>
        internal static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:not([hidden]) vb-band-button#band-btn-upload.vb-disabled.
        /// </summary>
        internal static string UploadDisabledButton {
            get {
                return ResourceManager.GetString("UploadDisabledButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;Upload has been successfully completed&quot;).
        /// </summary>
        internal static string UploadSuccessfulDialog {
            get {
                return ResourceManager.GetString("UploadSuccessfulDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal div:contains(&quot;have access&quot;).
        /// </summary>
        internal static string YouDontHaveAccessDialog {
            get {
                return ResourceManager.GetString("YouDontHaveAccessDialog", resourceCulture);
            }
        }
    }
}
