//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;player_resource&quot;:{&quot;id&quot;:&quot;HQ-player_resource_professional-1278&quot;,&quot;version&quot;:&quot;1.0.0&quot;},&quot;player_livepreviewmode&quot;:false,&quot;player_debugmode&quot;:false,&quot;topMost&quot;:true,&quot;MainVolume&quot;:0.3,&quot;player_recording_quality&quot;:&quot;low&quot;,&quot;sampling_percentage&quot;:0,&quot;min_session_duration&quot;:10,&quot;expected_session_gestures&quot;:3,&quot;begin_recording_delay&quot;:5,&quot;assetsKeepTime&quot;:&quot;twoWeeks&quot;,&quot;co_api_url&quot;:&quot;https://co-api.azurewebsites.net/&quot;,&quot;co_sto_url&quot;:&quot;https://costoprd.blob.core.windows.net/assets/&quot;,&quot;idle_timeout&quot;:10,&quot;distanceToFineArea&quot;:1.2,&quot;fineAreaWidth&quot;:0.8, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComposerHq1ParameterInstance {
            get {
                return ResourceManager.GetString("ComposerHq1ParameterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;player_resource&quot;:{&quot;id&quot;:&quot;HQ-player_resource_professional-1314&quot;,&quot;version&quot;:&quot;1.0.0&quot;},&quot;player_livepreviewmode&quot;:false,&quot;player_debugmode&quot;:false,&quot;topMost&quot;:true,&quot;MainVolume&quot;:0.3,&quot;player_recording_quality&quot;:&quot;low&quot;,&quot;sampling_percentage&quot;:0,&quot;min_session_duration&quot;:10,&quot;expected_session_gestures&quot;:3,&quot;begin_recording_delay&quot;:5,&quot;assetsKeepTime&quot;:&quot;twoWeeks&quot;,&quot;co_api_url&quot;:&quot;https://co-api.azurewebsites.net/&quot;,&quot;co_sto_url&quot;:&quot;https://costoprd.blob.core.windows.net/assets/&quot;,&quot;idle_timeout&quot;:10,&quot;distanceToFineArea&quot;:1.2,&quot;fineAreaWidth&quot;:0.8, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ComposerHq2ParameterInstance {
            get {
                return ResourceManager.GetString("ComposerHq2ParameterInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002ebf12-a125-5ddf-a739-67c3c5d20177.
        /// </summary>
        internal static string DeviceAppUuidAndroid {
            get {
                return ResourceManager.GetString("DeviceAppUuidAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5311839E985FA01B56E7AD74334C0137F7D6AF71A22745D0FB50DED665E0E882.
        /// </summary>
        internal static string DeviceAppUuidIphone {
            get {
                return ResourceManager.GetString("DeviceAppUuidIphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;interiorColorDisclaimer&quot;:&quot;&quot;,&quot;imprintUrl&quot;:&quot;http://www.porsche.com/germany/legal-notice/&quot;,&quot;imprintClass&quot;:&quot;b-standard-content-wrapper&quot;,&quot;primaryCopyrightClass&quot;:&quot;m-03-copyright&quot;,&quot;costOfAdditionalMileageOfLeasing&quot;:&quot;qwerty1&quot;,&quot;costOfLessMileageOfLeasing&quot;:&quot;qwerty2&quot;,&quot;unitForMileageOfLeasing&quot;:&quot;km&quot;,&quot;currencyFormatting&quot;:&quot;currencyFirst&quot;,&quot;pinCode&quot;:&quot;1234&quot;,&quot;market&quot;:&quot;QQ&quot;,&quot;stateResetTimer&quot;:300,&quot;displayBrightness&quot;:1}.
        /// </summary>
        internal static string DptMasterDataValuesDe {
            get {
                return ResourceManager.GetString("DptMasterDataValuesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;interiorColorDisclaimer&quot;:&quot;&quot;,&quot;imprintUrl&quot;:&quot;http://www.porsche.com/germany/legal-notice/&quot;,&quot;imprintClass&quot;:&quot;b-standard-content-wrapper&quot;,&quot;primaryCopyrightClass&quot;:&quot;m-03-copyright&quot;,&quot;costOfAdditionalMileageOfLeasing&quot;:&quot;qwerty1&quot;,&quot;costOfLessMileageOfLeasing&quot;:&quot;qwerty2&quot;,&quot;unitForMileageOfLeasing&quot;:&quot;miles&quot;,&quot;currencyFormatting&quot;:&quot;currencyFirst&quot;,&quot;pinCode&quot;:&quot;1234&quot;,&quot;market&quot;:&quot;QQ&quot;,&quot;stateResetTimer&quot;:300,&quot;displayBrightness&quot;:1}.
        /// </summary>
        internal static string DptMasterDataValuesEn {
            get {
                return ResourceManager.GetString("DptMasterDataValuesEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B426BC453CAC4F89BEA579DAB6C25564.
        /// </summary>
        internal static string IbeaconApiKey {
            get {
                return ResourceManager.GetString("IbeaconApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to porsche.beacon.mobileapp.
        /// </summary>
        internal static string IbeaconAppId {
            get {
                return ResourceManager.GetString("IbeaconAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///  &quot;id&quot;: &quot;http://virtualpromoter.com/schemas/porsche/beaconMasterData.json#&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;information&quot;: {
        ///      &quot;type&quot;: &quot;object&quot;,
        ///      &quot;properties&quot;: {
        ///        &quot;salutationWithProfile&quot;: {
        ///          &quot;type&quot;: &quot;string&quot;,
        ///          &quot;maxLength&quot;: 200
        ///        },
        ///        &quot;salutationWithoutProfile&quot;: {
        ///          &quot;type&quot;: &quot;string&quot;,
        ///          &quot;maxLength&quot;: 50
        ///        },
        ///        &quot;description&quot;: {
        ///          &quot;type&quot;: &quot;string&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IbeaconMasterData {
            get {
                return ResourceManager.GetString("IbeaconMasterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;information&quot;:{&quot;salutationWithProfile&quot;:&quot;DE TEST SALUTATION&quot;,&quot;picture&quot;:{&quot;assetId&quot;:&quot;3&quot;,&quot;mimeType&quot;:&quot;image/jpeg&quot;,&quot;width&quot;:200,&quot;height&quot;:150},&quot;addresses&quot;:[{&quot;title&quot;:&quot;address title&quot;,&quot;address1&quot;:&quot;TEST DE ADDRESS&quot;}],&quot;workingHours&quot;:[{&quot;title&quot;:&quot;title&quot;,&quot;description&quot;:&quot;description&quot;}],&quot;employees&quot;:[]},&quot;market&quot;:{&quot;market&quot;:&quot;AA&quot;,&quot;defaultCurrency&quot;:&quot;EUR&quot;,&quot;currencyFormatting&quot;:&quot;amountFirst&quot;},&quot;texts&quot;:{&quot;imprint&quot;:{&quot;imprintUrl&quot;:&quot;http://www.porsche.com/germany/legal-notice/&quot;,&quot;imprintClass&quot;:&quot;b-standard-content-wrapper&quot;},&quot;goodByeMessage&quot;:{&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IbeaconMasterDataValuesDe {
            get {
                return ResourceManager.GetString("IbeaconMasterDataValuesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;information&quot;:{&quot;salutationWithProfile&quot;:&quot;EN TEST SALUTATION&quot;,&quot;picture&quot;:{&quot;assetId&quot;:&quot;3&quot;,&quot;mimeType&quot;:&quot;image/jpeg&quot;,&quot;width&quot;:200,&quot;height&quot;:150},&quot;addresses&quot;:[{&quot;title&quot;:&quot;address title&quot;,&quot;address1&quot;:&quot;TEST EN ADDRESS&quot;}],&quot;workingHours&quot;:[{&quot;title&quot;:&quot;title&quot;,&quot;description&quot;:&quot;description&quot;}],&quot;employees&quot;:[]},&quot;market&quot;:{&quot;market&quot;:&quot;AA&quot;,&quot;defaultCurrency&quot;:&quot;EUR&quot;,&quot;currencyFormatting&quot;:&quot;amountFirst&quot;},&quot;texts&quot;:{&quot;imprint&quot;:{&quot;imprintUrl&quot;:&quot;http://www.porsche.com/germany/legal-notice/&quot;,&quot;imprintClass&quot;:&quot;b-standard-content-wrapper&quot;},&quot;goodByeMessage&quot;:{&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IbeaconMasterDataValuesEn {
            get {
                return ResourceManager.GetString("IbeaconMasterDataValuesEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E4DE3311-3EE5-4FA0-B410-BF2DCF29C210.
        /// </summary>
        internal static string IbeaconMobileApplicationId {
            get {
                return ResourceManager.GetString("IbeaconMobileApplicationId", resourceCulture);
            }
        }
    }
}
