//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UriCxm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UriCxm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resources.UriCxm", typeof(UriCxm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account/Login.
        /// </summary>
        public static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/MyIP.
        /// </summary>
        public static string AccountMyIp {
            get {
                return ResourceManager.GetString("AccountMyIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account/Register.
        /// </summary>
        public static string AccountRegister {
            get {
                return ResourceManager.GetString("AccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps/{0}.
        /// </summary>
        public static string AppById {
            get {
                return ResourceManager.GetString("AppById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approval.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approval/request.
        /// </summary>
        public static string ApproveRequest {
            get {
                return ResourceManager.GetString("ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps/CreateThumbnails.
        /// </summary>
        public static string AppsCreateThumbnails {
            get {
                return ResourceManager.GetString("AppsCreateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps?appVersionId={0}&amp;updatedDateTime={1}&amp;deleteCompletely={2}.
        /// </summary>
        public static string AppsDelete {
            get {
                return ResourceManager.GetString("AppsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps/getImageSas.
        /// </summary>
        public static string AppsGetImageSas {
            get {
                return ResourceManager.GetString("AppsGetImageSas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps/getPackageSas.
        /// </summary>
        public static string AppsGetPackageSas {
            get {
                return ResourceManager.GetString("AppsGetPackageSas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps/appVersion/{0}.
        /// </summary>
        public static string AppsGetVersion {
            get {
                return ResourceManager.GetString("AppsGetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps/Restore?appVersionId={0}&amp;updatedDateTime={1}.
        /// </summary>
        public static string AppsRestore {
            get {
                return ResourceManager.GetString("AppsRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apps?overwriteItems={0}.
        /// </summary>
        public static string AppsSave {
            get {
                return ResourceManager.GetString("AppsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset/CreateThumbnails.
        /// </summary>
        public static string AssetCreateThumbnails {
            get {
                return ResourceManager.GetString("AssetCreateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset/GetImageSas.
        /// </summary>
        public static string AssetGetImageSas {
            get {
                return ResourceManager.GetString("AssetGetImageSas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundTask.
        /// </summary>
        public static string BackgroundTask {
            get {
                return ResourceManager.GetString("BackgroundTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundTask/All.
        /// </summary>
        public static string BackgroundTaskAll {
            get {
                return ResourceManager.GetString("BackgroundTaskAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundTask/Execution.
        /// </summary>
        public static string BackgroundTaskExecution {
            get {
                return ResourceManager.GetString("BackgroundTaskExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackgroundTask/{0}.
        /// </summary>
        public static string BackgroundTaskId {
            get {
                return ResourceManager.GetString("BackgroundTaskId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days?fileName={0}.
        /// </summary>
        public static string DaysGetSas {
            get {
                return ResourceManager.GetString("DaysGetSas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days?sas={0}.
        /// </summary>
        public static string DaysImportFile {
            get {
                return ResourceManager.GetString("DaysImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devices.
        /// </summary>
        public static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devices?deviceTypeId={0}.
        /// </summary>
        public static string DevicesByDevicesTypeId {
            get {
                return ResourceManager.GetString("DevicesByDevicesTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to devices/{0}.
        /// </summary>
        public static string DevicesById {
            get {
                return ResourceManager.GetString("DevicesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items/{0}.
        /// </summary>
        public static string ItemById {
            get {
                return ResourceManager.GetString("ItemById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items/follow/{0}.
        /// </summary>
        public static string ItemsFollow {
            get {
                return ResourceManager.GetString("ItemsFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items/search?search={0}&amp;includeDeleted={1}.
        /// </summary>
        public static string ItemsSearch {
            get {
                return ResourceManager.GetString("ItemsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications/create?handle={0}.
        /// </summary>
        public static string NotificationsCreate {
            get {
                return ResourceManager.GetString("NotificationsCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications/{0}.
        /// </summary>
        public static string NotificationsDeleteRegistration {
            get {
                return ResourceManager.GetString("NotificationsDeleteRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications/register/{0}.
        /// </summary>
        public static string NotificationsRegister {
            get {
                return ResourceManager.GetString("NotificationsRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places/allRoots.
        /// </summary>
        public static string PlacesAllRoots {
            get {
                return ResourceManager.GetString("PlacesAllRoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places/{0}.
        /// </summary>
        public static string PlacesById {
            get {
                return ResourceManager.GetString("PlacesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places/CreateThumbnails.
        /// </summary>
        public static string PlacesCreateThumbnails {
            get {
                return ResourceManager.GetString("PlacesCreateThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places/{0}?deactivateChilds={1}.
        /// </summary>
        public static string PlacesDelete {
            get {
                return ResourceManager.GetString("PlacesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places/GetImageSas.
        /// </summary>
        public static string PlacesGetImageSas {
            get {
                return ResourceManager.GetString("PlacesGetImageSas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleEntry/New?packageVersionId={0}.
        /// </summary>
        public static string ScheduleEntry {
            get {
                return ResourceManager.GetString("ScheduleEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenants/exportingEntities.
        /// </summary>
        public static string TenantsExport {
            get {
                return ResourceManager.GetString("TenantsExport", resourceCulture);
            }
        }
    }
}
