//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UriUserDirectory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UriUserDirectory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Api.Resources.UriUserDirectory", typeof(UriUserDirectory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account/Login.
        /// </summary>
        internal static string AccountLogin {
            get {
                return ResourceManager.GetString("AccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications/List.
        /// </summary>
        internal static string ApplicationList {
            get {
                return ResourceManager.GetString("ApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions/GetSupportedPermissions?applicationId={0}.
        /// </summary>
        internal static string GetSupportedPermissions {
            get {
                return ResourceManager.GetString("GetSupportedPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/{0}.
        /// </summary>
        internal static string RoleById {
            get {
                return ResourceManager.GetString("RoleById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/List.
        /// </summary>
        internal static string RolesList {
            get {
                return ResourceManager.GetString("RolesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles/Save.
        /// </summary>
        internal static string RolesSave {
            get {
                return ResourceManager.GetString("RolesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants/Load?id={0}.
        /// </summary>
        internal static string TenantLoadById {
            get {
                return ResourceManager.GetString("TenantLoadById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants/Save.
        /// </summary>
        internal static string TenantSave {
            get {
                return ResourceManager.GetString("TenantSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenants/List.
        /// </summary>
        internal static string TenantsList {
            get {
                return ResourceManager.GetString("TenantsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/{0}.
        /// </summary>
        internal static string UserById {
            get {
                return ResourceManager.GetString("UserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/List.
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/Load?id={0}.
        /// </summary>
        internal static string UserLoad {
            get {
                return ResourceManager.GetString("UserLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users/Save.
        /// </summary>
        internal static string UserSave {
            get {
                return ResourceManager.GetString("UserSave", resourceCulture);
            }
        }
    }
}
