//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppTitle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppTitle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.AppTitle", typeof(AppTitle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer_HQ_App_1.
        /// </summary>
        public static string ComposerHq1 {
            get {
                return ResourceManager.GetString("ComposerHq1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer_HQ_App_2.
        /// </summary>
        public static string ComposerHq2 {
            get {
                return ResourceManager.GetString("ComposerHq2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer_VIPB_App.
        /// </summary>
        public static string ComposerVipB {
            get {
                return ResourceManager.GetString("ComposerVipB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer_VIPB_App_2.
        /// </summary>
        public static string ComposerVipB2 {
            get {
                return ResourceManager.GetString("ComposerVipB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration_Application_1.
        /// </summary>
        public static string ConfigurationApplication1 {
            get {
                return ResourceManager.GetString("ConfigurationApplication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche DPT.
        /// </summary>
        public static string Dpt {
            get {
                return ResourceManager.GetString("Dpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche_DPT_testmodel1.
        /// </summary>
        public static string DptRt09010 {
            get {
                return ResourceManager.GetString("DptRt09010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Distribute Porsche DPT.
        /// </summary>
        public static string DptRt11090 {
            get {
                return ResourceManager.GetString("DptRt11090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche Event Kit App.
        /// </summary>
        public static string EventKit {
            get {
                return ResourceManager.GetString("EventKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haribo_App.
        /// </summary>
        public static string Haribo {
            get {
                return ResourceManager.GetString("Haribo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche iBeacon App.
        /// </summary>
        public static string Ibeacon {
            get {
                return ResourceManager.GetString("Ibeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche iBeacon testmodel1.
        /// </summary>
        public static string IbeaconRt09020 {
            get {
                return ResourceManager.GetString("IbeaconRt09020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPad Player.
        /// </summary>
        public static string IpadPlayer {
            get {
                return ResourceManager.GetString("IpadPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legoboost.unity.
        /// </summary>
        public static string LegoBoostUnity {
            get {
                return ResourceManager.GetString("LegoBoostUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP_PORSCHE.
        /// </summary>
        public static string SapPorsche {
            get {
                return ResourceManager.GetString("SapPorsche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Dependencies Master Data.
        /// </summary>
        public static string TestDependenciesMd {
            get {
                return ResourceManager.GetString("TestDependenciesMd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Device Types.
        /// </summary>
        public static string TestDeviceTypes {
            get {
                return ResourceManager.GetString("TestDeviceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Element Permission Porsche DPT.
        /// </summary>
        public static string TestElementPermissionDpt {
            get {
                return ResourceManager.GetString("TestElementPermissionDpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CayenneNew.
        /// </summary>
        public static string UeCarCayenneNew {
            get {
                return ResourceManager.GetString("UeCarCayenneNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain.
        /// </summary>
        public static string UeCarScenePlain {
            get {
                return ResourceManager.GetString("UeCarScenePlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CarViewer.
        /// </summary>
        public static string UeCarViewer {
            get {
                return ResourceManager.GetString("UeCarViewer", resourceCulture);
            }
        }
    }
}
