//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonElement {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonElement() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.CommonElement", typeof(CommonElement).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-modal-backdrop:visible.
        /// </summary>
        public static string Backdrop {
            get {
                return ResourceManager.GetString("Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.select2-search__field:visible.
        /// </summary>
        public static string DropDownInput {
            get {
                return ResourceManager.GetString("DropDownInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li.select2-results__option:contains(&quot;{0}&quot;):visible.
        /// </summary>
        public static string DropDownOption {
            get {
                return ResourceManager.GetString("DropDownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li.select2-results__option:has(div:empty):visible.
        /// </summary>
        public static string DropDownOptionEmpty {
            get {
                return ResourceManager.GetString("DropDownOptionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul.select2-results__options li.select2-results__option:visible.
        /// </summary>
        public static string DropDownOptionList {
            get {
                return ResourceManager.GetString("DropDownOptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb-fader-active.
        /// </summary>
        public static string Fader {
            get {
                return ResourceManager.GetString("Fader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal input.vb-band-input[placeholder=&quot;Filter&quot;]:visible.
        /// </summary>
        public static string FilterModal {
            get {
                return ResourceManager.GetString("FilterModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb-glob-fader.
        /// </summary>
        public static string GlobalFader {
            get {
                return ResourceManager.GetString("GlobalFader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb-notification-area.
        /// </summary>
        public static string InfoPopup {
            get {
                return ResourceManager.GetString("InfoPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main:visible.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.modal:visible.
        /// </summary>
        public static string ModalDialog1 {
            get {
                return ResourceManager.GetString("ModalDialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal:visible.
        /// </summary>
        public static string ModalDialog2 {
            get {
                return ResourceManager.GetString("ModalDialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb-modal vb-band-button.default:not([class*=&quot;vb-disabled&quot;]):visible.
        /// </summary>
        public static string ModalDialogDefaultButton1 {
            get {
                return ResourceManager.GetString("ModalDialogDefaultButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-modal vb-band-button.default:not([class*=&quot;vb-disabled&quot;]):visible.
        /// </summary>
        public static string ModalDialogDefaultButton2 {
            get {
                return ResourceManager.GetString("ModalDialogDefaultButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vb-band-base.
        /// </summary>
        public static string PageContent {
            get {
                return ResourceManager.GetString("PageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vb-loader:visible.
        /// </summary>
        public static string PageLoader {
            get {
                return ResourceManager.GetString("PageLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-app-img-progress:visible.
        /// </summary>
        public static string UploadImageProgress {
            get {
                return ResourceManager.GetString("UploadImageProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-upload-progress:visible.
        /// </summary>
        public static string UploadProgress {
            get {
                return ResourceManager.GetString("UploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-upload-spinner:visible.
        /// </summary>
        public static string UploadSpinner {
            get {
                return ResourceManager.GetString("UploadSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to span.vb-spin-warn:visible.
        /// </summary>
        public static string UploadWarning {
            get {
                return ResourceManager.GetString("UploadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.vb-validation-msg:visible.
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
    }
}
